import os
import glob
import json
import re
from datetime import datetime
from bs4 import BeautifulSoup

def generate():
    files = glob.glob("*.html")
    exclude = ["index.html", "404.html", "rajchannel.html", "fix-url.html", "skills.html"]
    posts = []

    cover_mapping = {
        "logic04.html": "assets/covers/banner_lego.webp",
        "logic05.html": "assets/covers/banner_pokemon.webp",
        "logic06.html": "assets/covers/banner_terraria.webp",
        "logic07.html": "assets/covers/banner_scratch.webp",
        "logic08.html": "assets/covers/banner_roblox.webp",
        "logic09.html": "assets/covers/banner_minecraft.webp",
        "logic10.html": "assets/covers/banner_amongus.webp",
        "logic11.html": "assets/covers/banner_fortnite.webp",
        "logic12.html": "assets/covers/banner_supermario.webp",
        "dom.html": "assets/covers/banner_animalcrossing.webp",

        "logic08.html": "assets/covers/banner_roblox.webp",
        "logic09.html": "assets/covers/banner_minecraft.webp",
        "logic10.html": "assets/covers/banner_amongus.webp",
        "logic11.html": "assets/covers/banner_fortnite.webp",
        "logic12.html": "assets/covers/banner_supermario.webp",
        "dom.html": "assets/covers/banner_animalcrossing.webp",

        "anton-osika-lovable.html": "https://media.fedu.vn/k_covers/3_body_problem_v2.webp",
        "ma-sat-noi-tam.html": "https://media.fedu.vn/k_covers/severance_v2.webp",
        "gs-po-shen-loh-ly-thuyet-tro-choi-giai-phap-song-sot-cho-con-nguoi-ky-nguyen-ai-podcast.html": "https://media.fedu.vn/k_covers/queens_gambit_v2.webp",
        "rick-rubin-ky-nang-duy-nhat-ai-khong-the-danh-cap-podcast.html": "https://media.fedu.vn/k_covers/dune_two_v2.webp",
        "tuong-lai-marketing-ban-do-phan-phoi-tu-0-dong-den-vo-han-ngan-sach-oren-john-podcast.html": "https://media.fedu.vn/k_covers/gentlemen_v2.webp",
        "logickenh-he-thong-hoa-storytelling-lat-cat-vi-mo.html": "https://media.fedu.vn/k_covers/shogun_v2.webp",
        "kichbanoffline-phau-thuat-kich-ban-offline-phan-6.html": "https://media.fedu.vn/k_covers/kichbanoffline-phau-thuat-kich-ban-offline-phan-6.webp",
        "kichbanoffline-phau-thuat-kich-ban-offline-phan-5.html": "https://media.fedu.vn/k_covers/kichbanoffline-phau-thuat-kich-ban-offline-phan-5.webp",
        "kichbanoffline-phau-thuat-kich-ban-offline-phan-4.html": "https://media.fedu.vn/k_covers/kichbanoffline-phau-thuat-kich-ban-offline-phan-4.webp",
        "kichbanoffline-phau-thuat-kich-ban-offline-phan-3.html": "https://media.fedu.vn/k_covers/kichbanoffline-phau-thuat-kich-ban-offline-phan-3.webp",
        "kichbanoffline-phau-thuat-kich-ban-offline-phan-2.html": "https://media.fedu.vn/k_covers/poster_278_1789613248069.webp",
        "kichbanoffline-phau-thuat-kich-ban-offline-phan-1.html": "https://media.fedu.vn/k_covers/kichbanoffline-phau-thuat-kich-ban-offline-phan-1.webp",
        "kichbanoffline-kich-ban-bds-30-phut-dap-tan-su-tri-hoan.html": "https://media.fedu.vn/k_covers/kichbanoffline-kich-ban-bds-30-phut-dap-tan-su-tri-hoan.webp",
        "kichbanoffline.html": "https://media.fedu.vn/k_covers/kichbanoffline.webp",
        "kichbanoffline-kich-ban-08-chuyen-mon-vung-nhung-vang-khach.html": "https://media.fedu.vn/k_covers/kichbanoffline-kich-ban-08-chuyen-mon-vung-nhung-vang-khach.webp",
        "kichbanoffline-phan-tich-video-fb-ads-6.html": "https://media.fedu.vn/k_covers/kichbanoffline-phan-tich-video-fb-ads-6.webp",
        "kichbanoffline-phan-tich-video-fb-ads-5.html": "https://media.fedu.vn/k_covers/kichbanoffline-phan-tich-video-fb-ads-5.webp",
        "kichbanoffline-phan-tich-video-fb-ads-4.html": "https://media.fedu.vn/k_covers/kichbanoffline-phan-tich-video-fb-ads-4.webp",
        "cong-thuc-1-kenh-de-phat-trien-podcast.html": "https://media.fedu.vn/k_covers/cong-thuc-1-kenh-de-phat-trien-podcast.webp",
        "so-tay-thuc-chien-khoi-nghiep-ky-nguyen-ai-podcast.html": "https://media.fedu.vn/k_covers/so-tay-thuc-chien-khoi-nghiep-ky-nguyen-ai-podcast.webp",
        "how-to-teach-and-grow-rich-business-model-podcast.html": "https://media.fedu.vn/k_covers/how-to-teach-and-grow-rich-business-model-podcast.webp",
        "10-protocols-andrew-huberman-toi-uu-nao-bo-the-chat-diary-of-a-ceo.html": "https://media.fedu.vn/k_covers/10-protocols-andrew-huberman-toi-uu-nao-bo-the-chat-diary-of-a-ceo.webp",
        "an-toan-ai-02-podcast.html": "https://media.fedu.vn/k_covers/poster_279_1789612783772.webp",
        "hau-qua-cua-nhin-linh-tinh-science.html": "https://media.fedu.vn/k_covers/poster_280_1789612830358.webp",
        "complex-5-anxiety-is-not-what-you-think.html": "https://media.fedu.vn/k_covers/complex-5-anxiety-is-not-what-you-think.webp",
        "suyash-saraf-d2c-branding-gen-z-marketing-podcast.html": "https://media.fedu.vn/k_covers/poster_281_1789612862471.webp",
        "law-5-stress-is-not-what-happens-to-you.html": "https://media.fedu.vn/k_covers/law-5-stress-is-not-what-happens-to-you.webp",
        "toi-uu-hieu-suat-nao-bo-suc-manh-nootropic-tu-creatine-va-che-do-an-thit-carnivore-dinh-cao-toi-gian-nang-luong-tu-joe-rogan-elon-musk.html": "https://media.fedu.vn/k_covers/toi-uu-hieu-suat-nao-bo-suc-manh-nootropic-tu-creatine-va-che-do-an-thit-carnivore-dinh-cao-toi-gian-nang-luong-tu-joe-rogan-elon-musk.webp",
        "su-giau-co-va-thanh-cong-tot-dinh-khong-bat-dau-tu-chien-thuat-kinh-doanh-hao-nhoang-ma-khoi-nguon-tu-nang-luc-quan-tri-tam-tri-ban-phai-thiet-ke-mot-moi-truong-khien-ky-luat-tro-nen-de-dang.html": "https://media.fedu.vn/k_covers/su-giau-co-va-thanh-cong-tot-dinh-khong-bat-dau-tu-chien-thuat-kinh-doanh-hao-nhoang-ma-khoi-nguon-tu-nang-luc-quan-tri-tam-tri-ban-phai-thiet-ke-mot-moi-truong-khien-ky-luat-tro-nen-de-dang.webp",
        "no-den-tu-long-dung-cam-dam-lam-ra-nhung-video-toi-te-ban-dau-kien-tri-cai-thien-1-moi-ngay-va-tap-trung-phuc-vu-sau-sac-cho-nhom-khan-gia-ngach-dang-chiu-chung-noi-dau-ma-ban-tung-vuot-qua-podcast.html": "https://media.fedu.vn/k_covers/no-den-tu-long-dung-cam-dam-lam-ra-nhung-video-toi-te-ban-dau-kien-tri-cai-thien-1-moi-ngay-va-tap-trung-phuc-vu-sau-sac-cho-nhom-khan-gia-ngach-dang-chiu-chung-noi-dau-ma-ban-tung-vuot-qua-podcast.webp",
        "be-khoa-thuat-toan-xay-kenh-niche-podcast.html": "https://media.fedu.vn/k_covers/be-khoa-thuat-toan-xay-kenh-niche-podcast.webp",
        "nghe-thuat-chuyen-minh-10-nam-dam-phan-hop-dong-molly-mcadam-podcast.html": "https://media.fedu.vn/k_covers/nghe-thuat-chuyen-minh-10-nam-dam-phan-hop-dong-molly-mcadam-podcast.webp",
        "co-the-ban-khong-he-ghet-ban-no-chi-dang-lam-xuat-sac-nhiem-vu-sinh-ton-bang-cach-bat-che-do-khang-cu-lai-su-sut-giam-calo-trong-mot-the.html": "https://media.fedu.vn/k_covers/co-the-ban-khong-he-ghet-ban-no-chi-dang-lam-xuat-sac-nhiem-vu-sinh-ton-bang-cach-bat-che-do-khang-cu-lai-su-sut-giam-calo-trong-mot-the.webp",
        "giac-ngu-hieu-suat-dinh-cao-science-long-form.html": "https://media.fedu.vn/k_covers/poster_282_1789613041805.webp",
        "dr-v-mohan-diabetes-sugar-genetics-health-podcast.html": "https://media.fedu.vn/k_covers/poster_283_1789612886392.webp",
        "su-thay-doi-khong-den-tu-viec-tim-kiem-mot-cuoc-song-de-dang-hon-ma-den-tu-viec-chu-dong-lua-chon-nhung-kho-khan-co-chu-dich-ap-luc-khong.html": "https://media.fedu.vn/k_covers/su-thay-doi-khong-den-tu-viec-tim-kiem-mot-cuoc-song-de-dang-hon-ma-den-tu-viec-chu-dong-lua-chon-nhung-kho-khan-co-chu-dich-ap-luc-khong.webp",
        "mat-ma-cua-su-loi-cuon-podcast-science.html": "https://media.fedu.vn/k_covers/mat-ma-cua-su-loi-cuon-podcast-science.webp",
        "co-hoc-luong-tu-va-truc-giac-tam-linh.html": "https://media.fedu.vn/k_covers/co-hoc-luong-tu-va-truc-giac-tam-linh.webp",
        "dr-joe-dispenza-rewire-brain-neuroplasticity-fear-podcast.html": "https://media.fedu.vn/k_covers/dr-joe-dispenza-rewire-brain-neuroplasticity-fear-podcast.webp",
        "hanh-trinh-khai-mo-sang-tao-chua-lanh-noi-dau-podcast.html": "https://media.fedu.vn/k_covers/hanh-trinh-khai-mo-sang-tao-chua-lanh-noi-dau-podcast.webp",
        "hanh-trinh-hack-nao-bo-science.html": "https://media.fedu.vn/k_covers/hanh-trinh-hack-nao-bo-science.webp",
        "chung-ta-khong-phai-la-nhung-co-may-thuan-ly-tri-co-the-thoat-khoi-quy-luat-sinh-hoc-con-nguoi-hien-dai-dang-van-hanh-bang-he-dieu-hanh-cua-to-tien-tren-thao-nguyen-podcast-science.html": "https://media.fedu.vn/k_covers/chung-ta-khong-phai-la-nhung-co-may-thuan-ly-tri-co-the-thoat-khoi-quy-luat-sinh-hoc-con-nguoi-hien-dai-dang-van-hanh-bang-he-dieu-hanh-cua-to-tien-tren-thao-nguyen-podcast-science.webp",
        "tamlyhoc-tam-ly-phong-thu-cua-nguoi-mua.html": "https://media.fedu.vn/k_covers/tamlyhoc-tam-ly-phong-thu-cua-nguoi-mua.webp",
        "he-thong-phuc-hop-prompt-4-giai-ma-ban-chat-he-dieu-hanh-vu-tru-va-kien-truc-nhan-thuc-bac-cao.html": "https://media.fedu.vn/k_covers/he-thong-phuc-hop-prompt-4-giai-ma-ban-chat-he-dieu-hanh-vu-tru-va-kien-truc-nhan-thuc-bac-cao.webp",
        "tu-duy-van-hanh-cua-ceo-uber-science.html": "https://media.fedu.vn/k_covers/tu-duy-van-hanh-cua-ceo-uber-science.webp",
        "giai-phong-tam-tri-tu-co-the-podcast.html": "https://media.fedu.vn/k_covers/giai-phong-tam-tri-tu-co-the-podcast.webp",
        "dai-chien-tu-duy-tranh-luan-nay-lua-giua-kevin-oleary-cenk-uygur-ve-tac-dong-cua-ai-den-that-nghiep-cuoc-dua-dia-chinh-tri-my-trung-va.html": "https://media.fedu.vn/k_covers/dai-chien-tu-duy-tranh-luan-nay-lua-giua-kevin-oleary-cenk-uygur-ve-tac-dong-cua-ai-den-that-nghiep-cuoc-dua-dia-chinh-tri-my-trung-va.webp",
        "xay-kenh-tam-ly-sang-tao-bai-hoc-tu-theo-von-fiona-cauley-science-podcast.html": "https://media.fedu.vn/k_covers/xay-kenh-tam-ly-sang-tao-bai-hoc-tu-theo-von-fiona-cauley-science-podcast.webp",
        "satinder-sartaaj-sufi-music-culture-fame-podcast.html": "https://media.fedu.vn/k_covers/satinder-sartaaj-sufi-music-culture-fame-podcast.webp",
        "dan-martell-ai-strategy-for-entrepreneurs-podcast.html": "https://media.fedu.vn/k_covers/dan-martell-ai-strategy-for-entrepreneurs-podcast.webp",
        "andrew-huberman-daily-habits-neuroscience-podcast.html": "https://media.fedu.vn/k_covers/andrew-huberman-daily-habits-neuroscience-podcast.webp",
        "masterclass-giai-ma-suc-khoe-sinh-ly-khoai-cam-nu-dr-rachel-rubin-podcast.html": "https://media.fedu.vn/k_covers/masterclass-giai-ma-suc-khoe-sinh-ly-khoai-cam-nu-dr-rachel-rubin-podcast.webp",
        "tuoi-30-khong-phai-la-luc-ban-bat-dau-gia-di-ma-la-thoi-diem-moi-thoi-quen-cua-ban-bat-dau-tinh-lai-kep-podcast.html": "https://media.fedu.vn/k_covers/tuoi-30-khong-phai-la-luc-ban-bat-dau-gia-di-ma-la-thoi-diem-moi-thoi-quen-cua-ban-bat-dau-tinh-lai-kep-podcast.webp",
        "ngu-day-chay-nuoc-mui-science.html": "https://media.fedu.vn/k_covers/ngu-day-chay-nuoc-mui-science.webp",
        "su-tai-sinh-thuc-su-khong-bao-gio-bat-dau-bang-viec-co-gang-va-viu-lai-phien-ban-cu-no-bat-dau-bang-long-dung-cam-de-chon-vui-nhung-lop-vo.html": "https://media.fedu.vn/k_covers/su-tai-sinh-thuc-su-khong-bao-gio-bat-dau-bang-viec-co-gang-va-viu-lai-phien-ban-cu-no-bat-dau-bang-long-dung-cam-de-chon-vui-nhung-lop-vo.webp",
        "toan-hoc-va-dau-tu-1-science.html": "https://media.fedu.vn/k_covers/toan-hoc-va-dau-tu-1-science.webp",
        "get-rich-off-salary-money-masterclass-podcast.html": "https://media.fedu.vn/k_covers/get-rich-off-salary-money-masterclass-podcast.webp",
        "tien-bac-chi-tieu-podcast.html": "https://media.fedu.vn/k_covers/tien-bac-chi-tieu-podcast.webp",
        "toi-uu-ram-nho-05-nhom-4-mo-van-sang-tao-sau-nap-du-lieu-science.html": "https://media.fedu.vn/k_covers/toi-uu-ram-nho-05-nhom-4-mo-van-sang-tao-sau-nap-du-lieu-science.webp",
        "oi-uu-ram-nho-03-nhom-2-van-hanh-trong-ngay-science.html": "https://media.fedu.vn/k_covers/oi-uu-ram-nho-03-nhom-2-van-hanh-trong-ngay-science.webp",
        "gioi-han-cua-y-chi-nguoi-quan-tuong-03-spiritual-science.html": "https://media.fedu.vn/k_covers/gioi-han-cua-y-chi-nguoi-quan-tuong-03-spiritual-science.webp",
        "cach-hoc-that-tu-insta-science.html": "https://media.fedu.vn/k_covers/cach-hoc-that-tu-insta-science.webp",
        "ban-khong-the-kien-tao-mot-cuoc-doi-co-y-nghia-bang-hanh-phuc-hoi-hot-hay-viec-dong-vai-nan-nhan-science.html": "https://media.fedu.vn/k_covers/ban-khong-the-kien-tao-mot-cuoc-doi-co-y-nghia-bang-hanh-phuc-hoi-hot-hay-viec-dong-vai-nan-nhan-science.webp",
        "nang-luc-cat-bo-bot-cac-lop-dinh-danh-ao-science.html": "https://media.fedu.vn/k_covers/nang-luc-cat-bo-bot-cac-lop-dinh-danh-ao-science.webp",
        "ham-luoi-mat-tay-tho-02-science.html": "https://media.fedu.vn/k_covers/ham-luoi-mat-tay-tho-02-science.webp",
        "law-4-ai-made-iq-and-eq-accessible.html": "https://media.fedu.vn/k_covers/law-4-ai-made-iq-and-eq-accessible.webp",
        "giai-ma-su-chan-thuc-kien-truc-noi-dung-podcast.html": "https://media.fedu.vn/k_covers/giai-ma-su-chan-thuc-kien-truc-noi-dung-podcast.webp",
        "mokksh-sani-liquor-retail-business-economics-podcast.html": "https://media.fedu.vn/k_covers/mokksh-sani-liquor-retail-business-economics-podcast.webp",
        "kiem-soat-insulin-science.html": "https://media.fedu.vn/k_covers/kiem-soat-insulin-science.webp",
        "khong-phai-la-nham-mat-kien-tri-ma-la-su-kien-tri-thu-nghiem-lien-tuc-podcast.html": "https://media.fedu.vn/k_covers/khong-phai-la-nham-mat-kien-tri-ma-la-su-kien-tri-thu-nghiem-lien-tuc-podcast.webp",
        "chua-lanh-dua-tre-ben-trong-podcast.html": "https://media.fedu.vn/k_covers/chua-lanh-dua-tre-ben-trong-podcast.webp",
        "kien-truc-thuc-tai-buc-man-ao-giac-science.html": "https://media.fedu.vn/k_covers/kien-truc-thuc-tai-buc-man-ao-giac-science.webp",
        "sell-your-knowledge-make-money-online-podcast.html": "https://media.fedu.vn/k_covers/sell-your-knowledge-make-money-online-podcast.webp",
        "su-thuc-tinh-ky-nguyen-ai-mentor-insight-podcast.html": "https://media.fedu.vn/k_covers/su-thuc-tinh-ky-nguyen-ai-mentor-insight-podcast.webp",
        "ganh-nang-cua-su-dang-do-science.html": "https://media.fedu.vn/k_covers/ganh-nang-cua-su-dang-do-science.webp",
        "hanh-trinh-thuc-tinh-nhe-nhang-podcast.html": "https://media.fedu.vn/k_covers/hanh-trinh-thuc-tinh-nhe-nhang-podcast.webp",
        "dung-cho-doi-dong-luc-vi-no-la-mot-loi-noi-doi-su-thay-doi-thuc-su-chi-bat-dau-khi-ban-ep-ban-than-hanh-dong-truoc-khi-cam-xuc-kip-len.html": "https://media.fedu.vn/k_covers/dung-cho-doi-dong-luc-vi-no-la-mot-loi-noi-doi-su-thay-doi-thuc-su-chi-bat-dau-khi-ban-ep-ban-than-hanh-dong-truoc-khi-cam-xuc-kip-len.webp",
        "brilliant-content-ideas-easier-than-ai-podcast.html": "https://media.fedu.vn/k_covers/brilliant-content-ideas-easier-than-ai-podcast.webp",
        "sieu-tri-tue-asi-podcast.html": "https://media.fedu.vn/k_covers/sieu-tri-tue-asi-podcast.webp",
        "hanh-trinh-tim-kiem-ban-doi-loi-giai-tu-noi-tam-science-long-form.html": "https://media.fedu.vn/k_covers/hanh-trinh-tim-kiem-ban-doi-loi-giai-tu-noi-tam-science-long-form.webp",
        "giai-ma-tuoi-tho-dinh-duong-thuc-vat-podcast.html": "https://media.fedu.vn/k_covers/giai-ma-tuoi-tho-dinh-duong-thuc-vat-podcast.webp",
        "khai-phong-tiem-nang-sang-tao.html": "https://media.fedu.vn/k_covers/khai-phong-tiem-nang-sang-tao.webp",
        "bi-quyet-giu-chan-nguoi-xem-trong-3-giay-dau-podcast.html": "https://media.fedu.vn/k_covers/bi-quyet-giu-chan-nguoi-xem-trong-3-giay-dau-podcast.webp",
        "thien-boc-dong-va-hieu-suat-cong-viec.html": "https://media.fedu.vn/k_covers/thien-boc-dong-va-hieu-suat-cong-viec.webp",
        "10m-ceo-why-ceos-need-personal-brand-podcast.html": "https://media.fedu.vn/k_covers/10m-ceo-why-ceos-need-personal-brand-podcast.webp",
        "5-danh-muc-quay-pho-bien.html": "https://media.fedu.vn/k_covers/5-danh-muc-quay-pho-bien.webp",
        "so-tay-sinh-ton-ky-nguyen-ai-2026-2027-mo-gawdat-podcast.html": "https://media.fedu.vn/k_covers/so-tay-sinh-ton-ky-nguyen-ai-2026-2027-mo-gawdat-podcast.webp",
        "he-thong-phan-bo-dong-tien-chan-dung-ro-ri-cam-xuc-hay-khong-podcast-science.html": "https://media.fedu.vn/k_covers/he-thong-phan-bo-dong-tien-chan-dung-ro-ri-cam-xuc-hay-khong-podcast-science.webp",
        "bi-quyet-tu-tin-camera.html": "https://media.fedu.vn/k_covers/bi-quyet-tu-tin-camera.webp",
        "vanessa-van-edwards-nghe-thuat-ket-noi-giao-tiep-dinh-cao-podcast.html": "https://media.fedu.vn/k_covers/vanessa-van-edwards-nghe-thuat-ket-noi-giao-tiep-dinh-cao-podcast.webp",
        "giai-ma-y-nghia-cuoc-song-cai-chet.html": "https://media.fedu.vn/k_covers/giai-ma-y-nghia-cuoc-song-cai-chet.webp",
        "hanh-trinh-chua-lanh-khoi-sinh-tu-bong-toi-macklemore-science-podcast.html": "https://media.fedu.vn/k_covers/hanh-trinh-chua-lanh-khoi-sinh-tu-bong-toi-macklemore-science-podcast.webp",
        "98-founder-dang-tu-giam-minh-trong-mot-nha-tu-tra-luong-cao-podcast.html": "https://media.fedu.vn/k_covers/98-founder-dang-tu-giam-minh-trong-mot-nha-tu-tra-luong-cao-podcast.webp",
        "kien-truc-toi-uu-hoa-nao-bo-hanh-vi-science.html": "https://media.fedu.vn/k_covers/kien-truc-toi-uu-hoa-nao-bo-hanh-vi-science.webp",
        "hanh-trinh-tinh-thuc-kham-pha-ban-nga-loi-giai-tu-mooji-ve-tinh-yeu-tinh-thuc-ru-bo-chap-niem-va-danh-thuc-ngon-lua-tri-tue-ben-trong-ban.html": "https://media.fedu.vn/k_covers/hanh-trinh-tinh-thuc-kham-pha-ban-nga-loi-giai-tu-mooji-ve-tinh-yeu-tinh-thuc-ru-bo-chap-niem-va-danh-thuc-ngon-lua-tri-tue-ben-trong-ban.webp",
        "tai-sao-giay-but-danh-bai-ban-phim-science.html": "https://media.fedu.vn/k_covers/tai-sao-giay-but-danh-bai-ban-phim-science.webp",
        "so-tay-tri-thuc-song-khong-hoi-tiec-podcast.html": "https://media.fedu.vn/k_covers/so-tay-tri-thuc-song-khong-hoi-tiec-podcast.webp",
        "ngung-do-loi-cho-gen-xau-hay-so-phan-moi-roi-loan-tam-ly-tu-tram-cam-lo-au-adhd-den-tu-ky-ve-ban-chat-sau-xa-nhat-deu-la-roi-loan-chuyen.html": "https://media.fedu.vn/k_covers/ngung-do-loi-cho-gen-xau-hay-so-phan-moi-roi-loan-tam-ly-tu-tram-cam-lo-au-adhd-den-tu-ky-ve-ban-chat-sau-xa-nhat-deu-la-roi-loan-chuyen.webp",
        "real-youtube-advice-for-real-entrepreneurs-podcast.html": "https://media.fedu.vn/k_covers/real-youtube-advice-for-real-entrepreneurs-podcast.webp",
        "meylin-va-66-ngay-science.html": "https://media.fedu.vn/k_covers/meylin-va-66-ngay-science.webp",
        "ban-dang-bi-dieu-khien-boi-chinh-cam-xuc-cua-minh-su-khac-biet-giua-nguoi-lam-chu-cuoc-choi-va-ke-bi-thao-tung-nam-o-cho-ke-bi-thao-tung.html": "https://media.fedu.vn/k_covers/ban-dang-bi-dieu-khien-boi-chinh-cam-xuc-cua-minh-su-khac-biet-giua-nguoi-lam-chu-cuoc-choi-va-ke-bi-thao-tung-nam-o-cho-ke-bi-thao-tung.webp",
        "life-knowledge-02-science-long-form.html": "https://media.fedu.vn/k_covers/life-knowledge-02-science-long-form.webp",
        "tri-tue-ngan-nam-cua-thieu-lam-podcast.html": "https://media.fedu.vn/k_covers/tri-tue-ngan-nam-cua-thieu-lam-podcast.webp",
        "thay-doi-thoi-quen-ket-luan-chi-quan-sat.html": "https://media.fedu.vn/k_covers/thay-doi-thoi-quen-ket-luan-chi-quan-sat.webp",
        "viec-dat-muc-tieu-chi-cho-rieng-minh-mua-nha-co-6-mui-vo-dich-la-mot-tro-choi-huu-han-choi-xong-la-tram-cam-science-long-form.html": "https://media.fedu.vn/k_covers/viec-dat-muc-tieu-chi-cho-rieng-minh-mua-nha-co-6-mui-vo-dich-la-mot-tro-choi-huu-han-choi-xong-la-tram-cam-science-long-form.webp",
        "fastest-way-to-monetize-content-longform-podcast.html": "https://media.fedu.vn/k_covers/fastest-way-to-monetize-content-longform-podcast.webp",
        "tai-sao-ko-xem-truoc-2h15-science.html": "https://media.fedu.vn/k_covers/tai-sao-ko-xem-truoc-2h15-science.webp",
        "chien-luoc-su-nghiep-top-1-tuyen-dung-ky-nguyen-ai-silicon-valley-girl.html": "https://media.fedu.vn/k_covers/chien-luoc-su-nghiep-top-1-tuyen-dung-ky-nguyen-ai-silicon-valley-girl.webp",
        "su-troi-day-cua-y-thuc-may-moc-podcast.html": "https://media.fedu.vn/k_covers/su-troi-day-cua-y-thuc-may-moc-podcast.webp",
        "hanh-trinh-tam-linh-spiritual.html": "https://media.fedu.vn/k_covers/hanh-trinh-tam-linh-spiritual.webp",
        "tim-hieu-o-cung-hagibis-science.html": "https://media.fedu.vn/k_covers/tim-hieu-o-cung-hagibis-science.webp",
        "so-tay-co-van-xay-dung-doanh-nghiep-ai-first-podcast.html": "https://media.fedu.vn/k_covers/so-tay-co-van-xay-dung-doanh-nghiep-ai-first-podcast.webp",
        "hammat-vai-ban-tay-mo-ho-tro-thien-dinh-science.html": "https://media.fedu.vn/k_covers/hammat-vai-ban-tay-mo-ho-tro-thien-dinh-science.webp",
        "moi-doanh-nghiep-that-bai-trong-viec-chot-sale-vi-mac-benh-ai-ky-thich-noi-ve-su-menh-cua-minh-thay-vi-giai-quyet-noi-dau-dang-chay-mau-cua-khach-hang-podcast-science.html": "https://media.fedu.vn/k_covers/moi-doanh-nghiep-that-bai-trong-viec-chot-sale-vi-mac-benh-ai-ky-thich-noi-ve-su-menh-cua-minh-thay-vi-giai-quyet-noi-dau-dang-chay-mau-cua-khach-hang-podcast-science.webp",
        "landing-page-giai-ma-hanh-vi-loi-ich-vo-ly-02-science.html": "https://media.fedu.vn/k_covers/landing-page-giai-ma-hanh-vi-loi-ich-vo-ly-02-science.webp",
        "hanh-trinh-chua-lanh-tai-sinh-science-podcast.html": "https://media.fedu.vn/k_covers/hanh-trinh-chua-lanh-tai-sinh-science-podcast.webp",
        "behavior-discipline-architecture-science.html": "https://media.fedu.vn/k_covers/behavior-discipline-architecture-science.webp",
        "ban-chat-cua-cam-nhan-thien-nhien-02.html": "https://media.fedu.vn/k_covers/ban-chat-cua-cam-nhan-thien-nhien-02.webp",
        "88-dan-so-dang-hong-he-thong-trao-doi-chat-tu-ben-trong-chia-khoa-khong-phai-la-tinh-calo-hay-chay-bo-ma-la-ngung-nap-thuc-pham-sieu-che.html": "https://media.fedu.vn/k_covers/88-dan-so-dang-hong-he-thong-trao-doi-chat-tu-ben-trong-chia-khoa-khong-phai-la-tinh-calo-hay-chay-bo-ma-la-ngung-nap-thuc-pham-sieu-che.webp",
        "nang-luong-song-qua-quan-sat.html": "https://media.fedu.vn/k_covers/nang-luong-song-qua-quan-sat.webp",
        "amcc-book-typo.html": "https://media.fedu.vn/k_covers/amcc-book-typo.webp",
        "prashant-desai-protein-metabolic-health-muscle-podcast.html": "https://media.fedu.vn/k_covers/prashant-desai-protein-metabolic-health-muscle-podcast.webp",
        "kichbanoffline-01-vuong-the-dien-truoc-ong-kinh.html": "https://media.fedu.vn/k_covers/kichbanoffline-01-vuong-the-dien-truoc-ong-kinh.webp",
        "complex-8-the-skill-you-need-agility.html": "https://media.fedu.vn/k_covers/complex-8-the-skill-you-need-agility.webp",
        "sales-khong-phai-la-thao-tung-no-la-quyen-luc-mem-podcast.html": "https://media.fedu.vn/k_covers/sales-khong-phai-la-thao-tung-no-la-quyen-luc-mem-podcast.webp",
        "5-nganh-nghe-bien-mat-khi-ai-tang-toc.html": "https://media.fedu.vn/k_covers/5-nganh-nghe-bien-mat-khi-ai-tang-toc.webp",
        "troi-buoc-tien-hoa-science.html": "https://media.fedu.vn/k_covers/troi-buoc-tien-hoa-science.webp",
        "deepthink-03-podcast-dashboard-science-podcast.html": "https://media.fedu.vn/k_covers/deepthink-03-podcast-dashboard-science-podcast.webp",
        "thanh-cong-tot-dinh-khong-den-tu-viec-sao-chep-nhung-ke-dung-dau-ma-den-tu-viec-ban-kien-nhan-chiu-dung-su-nhat-nheo-trong-bong-toi-suot.html": "https://media.fedu.vn/k_covers/thanh-cong-tot-dinh-khong-den-tu-viec-sao-chep-nhung-ke-dung-dau-ma-den-tu-viec-ban-kien-nhan-chiu-dung-su-nhat-nheo-trong-bong-toi-suot.webp",
        "how-to-make-100k-selling-your-knowledge-podcast.html": "https://media.fedu.vn/k_covers/how-to-make-100k-selling-your-knowledge-podcast.webp",
        "ashwin-srivastava-harvard-mba-frameworks-career-podcast.html": "https://media.fedu.vn/k_covers/ashwin-srivastava-harvard-mba-frameworks-career-podcast.webp",
        "nghe-thuat-cua-nhung-quyet-dinh-vi-dai-podcast.html": "https://media.fedu.vn/k_covers/nghe-thuat-cua-nhung-quyet-dinh-vi-dai-podcast.webp",
        "fix-this-core-bottleneck-business-success-podcast.html": "https://media.fedu.vn/k_covers/fix-this-core-bottleneck-business-success-podcast.webp",
        "dr-k-relationship-psychology-trauma-podcast.html": "https://media.fedu.vn/k_covers/dr-k-relationship-psychology-trauma-podcast.webp",
        "noi-dau-va-nhung-goc-toi-tam-nhat-cua-con-nguoi-khong-phai-la-thu-de-choi-bo-no-la-canh-cua-bat-buoc-phai-di-qua-de-dat-duoc-su-thuc-tinh.html": "https://media.fedu.vn/k_covers/noi-dau-va-nhung-goc-toi-tam-nhat-cua-con-nguoi-khong-phai-la-thu-de-choi-bo-no-la-canh-cua-bat-buoc-phai-di-qua-de-dat-duoc-su-thuc-tinh.webp",
        "99-percent-online-businesses-replaced-content-podcast.html": "https://media.fedu.vn/k_covers/99-percent-online-businesses-replaced-content-podcast.webp",
        "giai-ma-ap-luc-nuoi-day-con-thanh-cong-podcast-science.html": "https://media.fedu.vn/k_covers/giai-ma-ap-luc-nuoi-day-con-thanh-cong-podcast-science.webp",
        "hack-tien-hoa-toi-uu-nao-spiritual.html": "https://media.fedu.vn/k_covers/hack-tien-hoa-toi-uu-nao-spiritual.webp",
        "cach-kiem-soat-khung-hinh-khi-quay-science.html": "https://media.fedu.vn/k_covers/cach-kiem-soat-khung-hinh-khi-quay-science.webp",
        "thiet-ke-cuoc-song-phong-phu-khong-can-phai-tan-tien-podcast.html": "https://media.fedu.vn/k_covers/thiet-ke-cuoc-song-phong-phu-khong-can-phai-tan-tien-podcast.webp",
        "tamlyhoc-18-phan-xa-giu-the-dien.html": "https://media.fedu.vn/k_covers/tamlyhoc-18-phan-xa-giu-the-dien.webp",
        "giai-ma-tam-thuc-7-nguyen-tac-hermetic-podcast.html": "https://media.fedu.vn/k_covers/giai-ma-tam-thuc-7-nguyen-tac-hermetic-podcast.webp",
        "life-knowledge-01-long-form.html": "https://media.fedu.vn/k_covers/life-knowledge-01-long-form.webp",
        "gut-health-masterclass-giai-ma-he-vi-sinh-duong-ruot-podcast.html": "https://media.fedu.vn/k_covers/gut-health-masterclass-giai-ma-he-vi-sinh-duong-ruot-podcast.webp",
        "thuat-toan-trieu-view-shorts-mathis-bolt-motiversity-podcast.html": "https://media.fedu.vn/k_covers/thuat-toan-trieu-view-shorts-mathis-bolt-motiversity-podcast.webp",
        "buoi-sang-khong-phai-la-luc-bat-dau-ngay-moi-no-la-luc-lap-trinh-he-dieu-hanh-cho-bo-nao-neu-ban-khong-chu-dong-viet-kich-ban-cho-tam-tri-su-lo-au-qua-khu-va-mang-xa-hoi-se-tu-dong-viet-thay-ban-podcast-science.html": "https://media.fedu.vn/k_covers/buoi-sang-khong-phai-la-luc-bat-dau-ngay-moi-no-la-luc-lap-trinh-he-dieu-hanh-cho-bo-nao-neu-ban-khong-chu-dong-viet-kich-ban-cho-tam-tri-su-lo-au-qua-khu-va-mang-xa-hoi-se-tu-dong-viet-thay-ban-podcast-science.webp",
        "suc-manh-cua-su-buong-bo-podcast-spiritual.html": "https://media.fedu.vn/k_covers/suc-manh-cua-su-buong-bo-podcast-spiritual.webp",
        "system-intelligence-architect-mo-gawdat.html": "https://media.fedu.vn/k_covers/system-intelligence-architect-mo-gawdat.webp",
        "thien-di-dao-va-tieu-hoa-science.html": "https://media.fedu.vn/k_covers/thien-di-dao-va-tieu-hoa-science.webp",
        "so-tay-trieu-do-khoi-nghiep-ky-nguyen-moi-cung-chu-tich-shopify-science-podcast.html": "https://media.fedu.vn/k_covers/so-tay-trieu-do-khoi-nghiep-ky-nguyen-moi-cung-chu-tich-shopify-science-podcast.webp",
        "lakshya-sen-olympic-champion-mindset-resilience-podcast.html": "https://media.fedu.vn/k_covers/lakshya-sen-olympic-champion-mindset-resilience-podcast.webp",
        "dung-viet-blog-nua-hay-xay-co-may-media-podcast.html": "https://media.fedu.vn/k_covers/dung-viet-blog-nua-hay-xay-co-may-media-podcast.webp",
        "tam-tri-khong-phai-la-mot-chiec-binh-de-cho-sut-me-theo-thoi-gian-no-la-mot-co-bap-it-nhat-45-den-70-cac-ca-sa-sut-tri-tue-dementia-hoan.html": "https://media.fedu.vn/k_covers/tam-tri-khong-phai-la-mot-chiec-binh-de-cho-sut-me-theo-thoi-gian-no-la-mot-co-bap-it-nhat-45-den-70-cac-ca-sa-sut-tri-tue-dementia-hoan.webp",
        "thien-it-dan-den-su-boc-dong.html": "https://media.fedu.vn/k_covers/thien-it-dan-den-su-boc-dong.webp",
        "lam-chu-tam-tri-ky-luat-podcast.html": "https://media.fedu.vn/k_covers/lam-chu-tam-tri-ky-luat-podcast.webp",
        "tai-sao-but-giay-danh-bai-ban-phim-science.html": "https://media.fedu.vn/k_covers/tai-sao-but-giay-danh-bai-ban-phim-science.webp",
        "giu-cho-duong-cong-glucose-cua-ban-phang-lang-podcast.html": "https://media.fedu.vn/k_covers/giu-cho-duong-cong-glucose-cua-ban-phang-lang-podcast.webp",
        "imtiaz-ali-filmmaking-storytelling-heartbreak-podcast.html": "https://media.fedu.vn/k_covers/imtiaz-ali-filmmaking-storytelling-heartbreak-podcast.webp",
        "thuong-hieu-ca-nhan-la-he-dieu-hanh-cua-doanh-nghiep-podcast.html": "https://media.fedu.vn/k_covers/thuong-hieu-ca-nhan-la-he-dieu-hanh-cua-doanh-nghiep-podcast.webp",
        "chung-ta-dang-song-trong-mot-thoi-dai-bi-thao-tung-boi-marketing-thuc-pham-chia-khoa-vang-khong-nam-o-viec-nap-that-nhieu-protein-hay-am.html": "https://media.fedu.vn/k_covers/chung-ta-dang-song-trong-mot-thoi-dai-bi-thao-tung-boi-marketing-thuc-pham-chia-khoa-vang-khong-nam-o-viec-nap-that-nhieu-protein-hay-am.webp",
        "trang-thai-co-the-quyet-dinh-suy-nghi-science.html": "https://media.fedu.vn/k_covers/trang-thai-co-the-quyet-dinh-suy-nghi-science.webp",
        "ao-anh-cua-su-ham-muon.html": "https://media.fedu.vn/k_covers/ao-anh-cua-su-ham-muon.webp",
        "giai-ma-ton-thuong-tam-ly-dr-gabor-mate-podcast.html": "https://media.fedu.vn/k_covers/giai-ma-ton-thuong-tam-ly-dr-gabor-mate-podcast.webp",
        "giai-ma-tuong-lai-cung-sam-altman-patrick-collison-podcast.html": "https://media.fedu.vn/k_covers/poster_513.webp",
        "complex-4-mo-gawdat-the-skill-you-need-in-the-age-of-ai.html": "https://media.fedu.vn/k_covers/poster_514.webp",
        "giai-ma-he-vi-sinh-duong-ruot-science-long-form.html": "https://media.fedu.vn/k_covers/poster_515.webp",
        "su-tien-hoa-he-sinh-thai-moi-elon-musk-podcast.html": "https://media.fedu.vn/k_covers/poster_516.webp",
        "kha-nang-tao-ra-khong-gian-an-toan-cho-minh-va-nguoi-khac-dung-khi-de-the-hien-con-nguoi-that-dau-tien-va-nghe-thuat-bien-nhung-tuong-tac-nhat-nheo-thanh-co-hoi-ket-noi-sau-sac-podcast.html": "https://media.fedu.vn/k_covers/poster_517.webp",
        "nghien-ngap-khong-phai-la-su-yeu-kem-ve-y-chi-ma-la-dau-hieu-cho-thay-nao-bo-dang-bi-doi-nhung-ket-noi-thuc-su-podcast.html": "https://media.fedu.vn/k_covers/poster_284_1789612900428.webp",
        "su-giai-phong-kinh-te-cua-phu-nu-la-mot-thanh-tuu-vi-dai-nhung-no-da-xe-bo-kich-ban-song-truyen-thong-cua-dan-ong-vai-tro-tru-cot-ma-chua-he-viet-lai-mot-kich-ban-moi-dan-ong-khong-doc-hai-ho-dang-roi-vao-khung-hoang-cua-su-vo-dung-podcast-science.html": "https://media.fedu.vn/k_covers/poster_285_1789613054083.webp",
        "nghe-thuat-thu-nghiem-nhanh-hang-tram-y-tuong-toi-voi-gia-re-mat-dep-bo-cai-toi-de-nhuong-cho-cho-nguoi-gioi-hon-va-giu-ky-luat-thep-voi-ranh-gioi-cuoc-song-podcast-science.html": "https://media.fedu.vn/k_covers/poster_286_1789613068457.webp",
        "troi-buoc-porn-other-science.html": "https://media.fedu.vn/k_covers/poster_287_1789613082475.webp",
        "khai-pha-suc-manh-sinh-hoc-tam-thuc-tai-lap-trinh-tiem-thuc-nho-ban-thiet-ke-epigenetics-va-tan-so-trai-tim-de-thiet-ke-so-phan-thien-duong.html": "https://media.fedu.vn/k_covers/poster_288_1789613094818.webp",
        "frank-walliser-bentley-luxury-automotive-podcast.html": "https://media.fedu.vn/k_covers/poster_289_1789613108788.webp",
        "giai-ma-spotify-tu-duy-cua-mot-ceo-huong-noi-science-long-form.html": "https://media.fedu.vn/k_covers/poster_290_1789613262649.webp",
        "wtf-is-wealth-ray-dalio-podcast.html": "https://media.fedu.vn/k_covers/poster_291_1789613131027.webp",
        "giai-ma-tam-thuc-tu-day-vuc-den-trieu-phu-podcast.html": "https://media.fedu.vn/k_covers/poster_292_1789613142475.webp",
        "tri-tue-he-thong-prompt-1-bao-cao-co-hoc-dong-luc-hoc-hanh-vi.html": "https://media.fedu.vn/k_covers/poster_295_1789613299042.webp",
        "ankur-warikoo-fake-life-money-psychology-podcast.html": "https://media.fedu.vn/k_covers/poster_296_1789613313929.webp",
        "ban-khong-can-yeu-100-cong-viec-chi-can-20-la-du-de-tao-ra-phep-mau-mien-nhiem-voi-su-kiet-suc-science-long-form.html": "https://media.fedu.vn/k_covers/poster_297_1789613323067.webp",
        "suc-khoe-doi-ban-chan-chinh-la-nen-mong-cho-kha-nang-van-dong-va-su-truong-tho-cua-toan-bo-co-the-podcast.html": "https://media.fedu.vn/k_covers/poster_298_1789613337071.webp",
        "ngoi-chan-moi-co-dong-luc-science.html": "https://media.fedu.vn/k_covers/poster_299_1789613349759.webp",
        "lap-trinh-bo-nao-01-science.html": "https://media.fedu.vn/k_covers/poster_300_1789613362843.webp",
        "dr-viju-jacob-spice-empire-fmcg-business-podcast.html": "https://media.fedu.vn/k_covers/dr-viju-jacob-spice-empire-fmcg-business-podcast.webp",
        "ky-luat-khong-phai-la-su-ep-buoc-dau-kho-ma-la-qua-trinh-thiet-ke-mot-he-thong-moi-truong-va-thoi-quen-sao-cho-viec-lam-dieu-dung-dan-tro.html": "https://media.fedu.vn/k_covers/ky-luat-khong-phai-la-su-ep-buoc-dau-kho-ma-la-qua-trinh-thiet-ke-mot-he-thong-moi-truong-va-thoi-quen-sao-cho-viec-lam-dieu-dung-dan-tro.webp",
        "complex-6-the-3-questions-that-end-unhappiness.html": "https://media.fedu.vn/k_covers/complex-6-the-3-questions-that-end-unhappiness.webp",
        "vo-hieu-hoa-lo-hong-y-chi-bang-tu-dong-hoa-tai-chinh-science.html": "https://media.fedu.vn/k_covers/poster_304.webp",
        "giai-ma-he-sinh-thai-duong-ruot-bo-nao-thu-hai-cua-co-the-science.html": "https://media.fedu.vn/k_covers/poster_305.webp",
        "myron-golden-first-million-charge-premium-podcast.html": "https://media.fedu.vn/k_covers/poster_306.webp",
        "empire-of-ai-kien-truc-du-lieu-rang-buoc-he-thong-myth-science.html": "https://media.fedu.vn/k_covers/poster_307.webp",
        "hanh-vi-cuong-che-va-loi-the-nao-bo-spiritual-science.html": "https://media.fedu.vn/k_covers/poster_308.webp",
        "chung-ta-khong-benh-vi-thieu-protein-hay-an-theo-che-do-low-fat-chung-ta-benh-vi-he-thong-cong-nghiep-thuc-pham-da-thao-tung-tam-ly-bien.html": "https://media.fedu.vn/k_covers/poster_309.webp",
        "giai-ma-luat-cua-mot-tam-thuc-khai-sang-podcast.html": "https://media.fedu.vn/k_covers/giai-ma-luat-cua-mot-tam-thuc-khai-sang-podcast.webp",
        "tinh-yeu-va-hon-nhan-khong-phai-la-mot-mon-qua-vinh-vien-chung-la-mot-khoan-vay-podcast.html": "https://media.fedu.vn/k_covers/tinh-yeu-va-hon-nhan-khong-phai-la-mot-mon-qua-vinh-vien-chung-la-mot-khoan-vay-podcast.webp",
        "giai-ma-nghe-podcast-sang-tao-noi-dung.html": "https://media.fedu.vn/k_covers/giai-ma-nghe-podcast-sang-tao-noi-dung.webp",
        "su-phan-nan-science.html": "https://media.fedu.vn/k_covers/poster_313.webp",
        "su-thay-doi-mang-tinh-buoc-ngoat-paradigm-shift-khong-den-tu-viec-ban-hieu-van-de-cua-minh-ma-den-tu-viec-ban-co-dam-buoc-ra-khoi-con-nghien-hoa-hoc-do-chinh-nhung-cam-xuc-dau-kho-trong-qua-khu-tao-ra-hay-khong-podcast.html": "https://media.fedu.vn/k_covers/su-thay-doi-mang-tinh-buoc-ngoat-paradigm-shift-khong-den-tu-viec-ban-hieu-van-de-cua-minh-ma-den-tu-viec-ban-co-dam-buoc-ra-khoi-con-nghien-hoa-hoc-do-chinh-nhung-cam-xuc-dau-kho-trong-qua-khu-tao-ra-hay-khong-podcast.webp",
        "dieu-huong-dopamine-deepthink-01-science.html": "https://media.fedu.vn/k_covers/poster_315.webp",
        "bo-nao-la-co-quan-ra-quyet-dinh-va-hinh-thanh-nhan-cach-cua-ban-khi-nao-hoat-dong-dung-ban-song-dung-podcast.html": "https://media.fedu.vn/k_covers/bo-nao-la-co-quan-ra-quyet-dinh-va-hinh-thanh-nhan-cach-cua-ban-khi-nao-hoat-dong-dung-ban-song-dung-podcast.webp",
        "discipline-architecture-2026-science.html": "https://media.fedu.vn/k_covers/cover_149.webp",
        "kinh-nguyet-la-mot-sinh-hieu-quan-trong-vital-sign-estrogen-va-progesterone-khong-chi-la-hormone-gioi-tinh-chung-la-nen-tang-dieu-khien-cau-truc-nao-bo-mat-do-xuong-va-suc-khoe-trao-doi-chat-cua-ban-suot-cuoc-doi-podcast-science.html": "https://media.fedu.vn/k_covers/poster_318.webp",
        "dopamine-architecture-science.html": "https://media.fedu.vn/k_covers/poster_319.webp",
        "su-tinh-thuc-dong-chay-thinh-vuong-podcast.html": "https://media.fedu.vn/k_covers/poster_320.webp",
        "doi-dien-bong-toi-dinh-hinh-lai-ky-luat-science-long-form.html": "https://media.fedu.vn/k_covers/cover_150.webp",
        "architecture-of-intelligence-mo-gawdat.html": "https://media.fedu.vn/k_covers/cover_151.webp",
        "jasmine-star-build-brand-automate-trust-podcast.html": "https://media.fedu.vn/k_covers/cover_152.webp",
        "su-cao-chung-cua-lao-dong-nhan-thuc-co-hoi-5050-cho-nhan-loai-science-podcast.html": "https://media.fedu.vn/k_covers/cover_153.webp",
        "giai-ma-suc-khoe-toan-dien-landing-page-podcast.html": "https://media.fedu.vn/k_covers/poster_325_ponyo.webp",
        "rajshamani-21-podcasts-hub.html": "https://media.fedu.vn/k_covers/poster_326_soul_2.webp",
        "khoa-hoc-toi-uu-hoa-nhan-thuc-can-thiep-than-kinh-science.html": "https://media.fedu.vn/k_covers/poster_327_creed_iii.webp",
        "personal-brand-blueprint-film-everything-podcast.html": "https://media.fedu.vn/k_covers/personal-brand-blueprint-film-everything-podcast.webp",
        "nao-bo-va-viec-chan-nan-science.html": "https://media.fedu.vn/k_covers/nao-bo-va-viec-chan-nan-science.webp",
        "the-one-skill-needed-to-make-millions-podcast.html": "https://media.fedu.vn/k_covers/the-one-skill-needed-to-make-millions-podcast.webp",
        "faith-and-wealth-spiritual-business-principles-podcast.html": "https://media.fedu.vn/k_covers/poster_331_bay_rong.webp",
        "moi-thanh-bai-trong-cuoc-doi-ban-khong-nam-o-ngoai-canh-ma-duoc-quyet-dinh-boi-3-truc-lam-chu-chinh-minh-quan-sat-sac-ben-va-giao-tiep-thau-cam-podcast.html": "https://media.fedu.vn/k_covers/poster_332_arcane.webp",
        "kichbanoffline-khi-nguoi-co-nghe-tu-tua-vao-huu-xa-tu-nhien-huong.html": "https://media.fedu.vn/k_covers/poster_333_no_game.webp",
        "ban-hang-la-ky-nang-song-podcast-science.html": "https://media.fedu.vn/k_covers/poster_334_sing.webp",
        "kien-tao-the-gioi-moi-charles-eisenstein-podcast.html": "https://media.fedu.vn/k_covers/poster_335_bi_dung_so.webp",
        "su-phi-ly-khi-lam-mot-con-nguoi-podcast.html": "https://media.fedu.vn/k_covers/poster_336_fallout.webp",
        "how-to-become-a-millionaire-start-teaching-podcast.html": "https://media.fedu.vn/k_covers/poster_337_hunter_x_hunter.webp",
        "omarchannel.html": "https://media.fedu.vn/k_covers/poster_338_shrek.webp",
        "su-that-ve-anh-sang-y-sinh-hoc-science.html": "https://media.fedu.vn/k_covers/poster_339_qua_tim_mau.webp",
        "kichbanoffline-dong-goi-bai-tu-van-thanh-video-1-phut.html": "https://media.fedu.vn/k_covers/poster_340_witcher.webp",
        "deepak-sahni-health-gut-liver-longevity-podcast.html": "https://media.fedu.vn/k_covers/poster_341_rezero.webp",
        "ban-khong-he-hong-hoc-ban-chi-dang-can-kiet-nguyen-lieu-de-van-hanh-science.html": "https://media.fedu.vn/k_covers/poster_342_powerpuff.webp",
        "kenh.html": "https://media.fedu.vn/k_covers/poster_343_trang_quynh.webp",
        "tai-sao-ban-lai-giam-iq-khi-co-tiet-kiem-bac-le-science.html": "https://media.fedu.vn/k_covers/poster_344_money_heist.webp",
        "nhin-mat-tre-em-va-nguoi-lon-science.html": "https://media.fedu.vn/k_covers/poster_345_psycho_pass.webp",
        "giai-ma-tinh-yeu-dich-thuc-nghe-thuat-chua-lanh.html": "https://media.fedu.vn/k_covers/poster_346_monsters_inc.webp",
        "giai-ma-tam-tri-loi-thoat-cho-mot-the-he-co-don-nghien-ngap-dr-k-science-long-form.html": "https://media.fedu.vn/k_covers/poster_347_ao_lua_ha_dong.webp",
        "mark-manson-psychology-of-love-toxic-relationships-podcast.html": "https://media.fedu.vn/k_covers/poster_348_peaky_blinders.webp",
        "architecture-of-an-ai-native-generation.html": "https://media.fedu.vn/k_covers/poster_349_kengan_ashura.webp",
        "ky-nguyen-abundance-tu-do-cong-nghe-giai-ma-elon-musk-science-long-form.html": "https://media.fedu.vn/k_covers/poster_353_chainsaw_man.webp",
        "tri-tue-ban-dia-siberi-snow-raven.html": "https://media.fedu.vn/k_covers/poster_354_cars.webp",
        "masterclass-giai-phau-ma-tran-ky-luat-thep-podcast.html": "https://media.fedu.vn/k_covers/poster_355_tam_cam.webp",
        "ban-khong-beo-vi-thieu-y-chi-ban-dang-bi-hack-nao-bo-science-long-form.html": "https://media.fedu.vn/k_covers/ban-khong-beo-vi-thieu-y-chi-ban-dang-bi-hack-nao-bo-science-long-form.webp",
        "david-eagleman-nao-bo-khong-phai-la-mot-co-may-co-dinh-ma-la-mot-he-sinh-thai-khong-ngung-tai-cau-truc-podcast.html": "https://media.fedu.vn/k_covers/david-eagleman-nao-bo-khong-phai-la-mot-co-may-co-dinh-ma-la-mot-he-sinh-thai-khong-ngung-tai-cau-truc-podcast.webp",
        "danh-thuc-niem-vui-nguyen-ban-podcast.html": "https://media.fedu.vn/k_covers/cover_159.webp",
        "tam-tri-khong-sinh-ra-de-chong-lai-ban-no-chi-dang-boi-roi-trong-no-luc-bao-ve-ban-podcast.html": "https://media.fedu.vn/k_covers/cover_160.webp",
        "su-xuat-sac-dich-thuc-khong-den-tu-viec-tu-vat-kiet-suc-luc-mot-cach-may-moc-no-la-nghe-thuat-dam-chim-vao-qua-trinh-duy-tri-mot-ngoi-nha.html": "https://media.fedu.vn/k_covers/cover_161.webp",
        "hanh-trinh-tai-sinh-su-nu-tinh-thau-hieu-bong-toi-ban-nga-nghe-thuat-can-bang-cuc-tinh-science-long-form.html": "https://media.fedu.vn/k_covers/cover_162.webp",
        "nexus-kien-truc-thong-tin-science.html": "https://media.fedu.vn/k_covers/nexus-kien-truc-thong-tin-science.webp",
        "ky-luat-giao-tiep-giai-ma-tam-ly-science.html": "https://media.fedu.vn/k_covers/ky-luat-giao-tiep-giai-ma-tam-ly-science.webp",
        "giai-ma-vu-tru-thuyet-tu-gia-lap-podcast.html": "https://media.fedu.vn/k_covers/giai-ma-vu-tru-thuyet-tu-gia-lap-podcast.webp",
        "xa-hoi-da-lua-chung-ta-rang-hanh-phuc-la-mot-loai-cam-xuc-thuc-chat-cam-xuc-chi-la-tin-hieu-hanh-phuc-thuc-su-la-mot-ky-nang-va-su-lua-chon.html": "https://media.fedu.vn/k_covers/xa-hoi-da-lua-chung-ta-rang-hanh-phuc-la-mot-loai-cam-xuc-thuc-chat-cam-xuc-chi-la-tin-hieu-hanh-phuc-thuc-su-la-mot-ky-nang-va-su-lua-chon.webp",
        "kichbanoffline-05-tiec-30-phut-lam-video-cho-ca-ngay.html": "https://media.fedu.vn/k_covers/kichbanoffline-05-tiec-30-phut-lam-video-cho-ca-ngay.webp",
        "how-to-get-rich-living-in-your-purpose-podcast.html": "https://media.fedu.vn/k_covers/cloudy_poster_53_1789843401910.webp",
        "thu-gian-va-tieu-hoa-co-che.html": "https://media.fedu.vn/k_covers/thu_gian_va_1789678317370.webp",
        "top-sales-expert-simple-sales-trick-money-podcast.html": "https://media.fedu.vn/k_covers/poster_369_top-sales-expert-simple-sales-trick-money-podcast.webp",
        "suc-khoe-tinh-duc-tuoi-tho-science.html": "https://media.fedu.vn/k_covers/suc_khoe_tinh_1789678326028.webp",
        "thien-kien-ca-nhan-hoa-sto.html": "https://media.fedu.vn/k_covers/thien_kien_ca_1789678392226.webp",
        "ban-hang-dinh-cao-tam-ly-hoc-chot-sale-shelby-sapp-podcast.html": "https://media.fedu.vn/k_covers/ban_hang_dinh_1789678412899.webp",
        "giao-tiep-phi-ngon-ngu-khong-phai-la-de-thao-tung-no-la-he-thong-canh-bao-sinh-ton-duoc-khac-sau-vao-dna-cua-chung-ta-viec-thau-hieu-no-giup-ban-kien-tao-su-thoai-mai-tam-ly-podcast.html": "https://media.fedu.vn/k_covers/giao_tiep_phi_1789678454080.webp",
        "daniel-podcast.html": "https://media.fedu.vn/k_covers/red_turtle_poster_54_1789843413460.webp",
        "ban-duoc-thiet-ke-de-song-podcast.html": "https://media.fedu.vn/k_covers/ban-duoc-thiet-ke-de-song-podcast.webp",
        "giai-ma-adn-than-thanh-mentor-learning.html": "https://media.fedu.vn/k_covers/giai-ma-adn-than-thanh-mentor-learning.webp",
        "elon-musk-on-doge-tuong-lai-cua-ban-phu-thuoc-vao-nang-luc-cat-dut-dong-ro-ri-nang-luong-podcast.html": "https://media.fedu.vn/k_covers/elon-musk-on-doge-tuong-lai-cua-ban-phu-thuoc-vao-nang-luc-cat-dut-dong-ro-ri-nang-luong-podcast.webp",
        "level-up-your-communication-skills-masterclass-podcast.html": "https://media.fedu.vn/k_covers/level-up-your-communication-skills-masterclass-podcast.webp",
        "mo-hoa.html": "https://media.fedu.vn/k_covers/mo-hoa.webp",
        "ung-thu-khong-phai-la-mot-can-benh-di-truyen-ngau-nhien-no-la-can-benh-roi-loan-chuyen-hoa-bat-nguon-tu-viec-ty-the-nha-may-nang-luong-cua-te-bao-bi-ton-thuong-keo-dai-podcast.html": "https://media.fedu.vn/k_covers/ung-thu-khong-phai-la-mot-can-benh-di-truyen-ngau-nhien-no-la-can-benh-roi-loan-chuyen-hoa-bat-nguon-tu-viec-ty-the-nha-may-nang-luong-cua-te-bao-bi-ton-thuong-keo-dai-podcast.webp",
        "thu-ban-nghi-minh-biet-ve-the-gioi-nay-chi-la-mot-mo-hinh-du-doan-podcast.html": "https://media.fedu.vn/k_covers/thu-ban-nghi-minh-biet-ve-the-gioi-nay-chi-la-mot-mo-hinh-du-doan-podcast.webp",
        "khoa-hoc-cua-chap-tay-spiritual-science.html": "https://media.fedu.vn/k_covers/khoa-hoc-cua-chap-tay-spiritual-science.webp",
        "su-thay-doi-thuc-su-khong-phai-la-co-gang-uon-nan-ban-than-thanh-mot-nguoi-hoan-toan-khac-no-la-qua-trinh-boc-tach-cac-lop-vo-boc-ao-tuong.html": "https://media.fedu.vn/k_covers/su-thay-doi-thuc-su-khong-phai-la-co-gang-uon-nan-ban-than-thanh-mot-nguoi-hoan-toan-khac-no-la-qua-trinh-boc-tach-cac-lop-vo-boc-ao-tuong.webp",
        "5-nghe-bien-mat.html": "https://media.fedu.vn/k_covers/5-nghe-bien-mat.webp",
        "he-thong-ai-second-brain-va-tu-dong-hoa-vaibhav-sisinty-podcast.html": "https://media.fedu.vn/k_covers/he-thong-ai-second-brain-va-tu-dong-hoa-vaibhav-sisinty-podcast.webp",
        "gioi-han-cua-y-chi-nguoi-quan-tuong-01.html": "https://media.fedu.vn/k_covers/gioi-han-cua-y-chi-nguoi-quan-tuong-01.webp",
        "nhan-ra-man-hinh-chieu-phim-cua-tam-thuc-podcast.html": "https://media.fedu.vn/k_covers/nhan-ra-man-hinh-chieu-phim-cua-tam-thuc-podcast.webp",
        "sunil-bajpai-fraud-scams-psychology-podcast.html": "https://media.fedu.vn/k_covers/sunil-bajpai-fraud-scams-psychology-podcast.webp",
        "sanjiv-goenka-wealth-turnaround-conglomerate-podcast.html": "https://media.fedu.vn/k_covers/sanjiv_goenka_wealth_1789678653869.webp",
        "kichbanoffline-phau-thuat-kich-ban-6.html": "https://media.fedu.vn/k_covers/kichbanoffline_phau_thuat_1789678691212.webp",
        "vi-sao-nguoi-khac-khong-thich-ban-podcast.html": "https://media.fedu.vn/k_covers/vi-sao-nguoi-khac-khong-thich-ban-podcast.webp",
        "shubhanshu-shukla-astronaut-space-zero-gravity-podcast.html": "https://media.fedu.vn/k_covers/shubhanshu-shukla-astronaut-space-zero-gravity-podcast.webp",
        "bill-ackman-kich-ban-dau-tu.html": "https://media.fedu.vn/k_covers/mad_men.webp",
        "youtube-masterclass-highest-paid-strategist.html": "https://media.fedu.vn/k_covers/my_hero_academia.webp",
        "banner.html": "https://media.fedu.vn/k_covers/banner.webp",
        "so-tay-xay-kenh-thuat-toan-mentor-nguyen-duc-viet-podcast.html": "https://media.fedu.vn/k_covers/so-tay-xay-kenh-thuat-toan-mentor-nguyen-duc-viet-podcast.webp",
        "tu-duy-ai-tu-dong-hoa-science.html": "https://media.fedu.vn/k_covers/tu-duy-ai-tu-dong-hoa-science.webp",
        "giai-ma-he-dieu-hanh-cua-elon-musk-podcast.html": "https://media.fedu.vn/k_covers/giai-ma-he-dieu-hanh-cua-elon-musk-podcast.webp",
        "ban-chat-cua-cam-nhan-thien-nhien-01.html": "https://media.fedu.vn/k_covers/ban-chat-cua-cam-nhan-thien-nhien-01.webp",
        "kichbanoffline-03-vuong-quy-trinh-solo.html": "https://media.fedu.vn/k_covers/kichbanoffline-03-vuong-quy-trinh-solo.webp",
        "danh-thuc-le-song-bang-dharma-tim-su-can-bang-giua-niem-vui-noi-tai-va-su-menh-phung-su-the-gioi-danh-cho-nhung-ai-dang-tran-tro-ve-dinh.html": "https://media.fedu.vn/k_covers/danh-thuc-le-song-bang-dharma-tim-su-can-bang-giua-niem-vui-noi-tai-va-su-menh-phung-su-the-gioi-danh-cho-nhung-ai-dang-tran-tro-ve-dinh.webp",
        "tai-sao-chi-2-moi-nguoi-thuc-su-but-pha-science-long-form.html": "https://media.fedu.vn/k_covers/tai-sao-chi-2-moi-nguoi-thuc-su-but-pha-science-long-form.webp",
        "dan-ong-tre-dang-mat-di-moi-truong-ren-luyen-su-ben-bi-tron-tranh-that-bai-bang-cac-lieu-dopamine-re-tien-porn-mxh-game-de-sinh-ton-nam-gioi-phai-dinh-nghia-lai-su-nam-tinh-podcast.html": "https://media.fedu.vn/k_covers/dan-ong-tre-dang-mat-di-moi-truong-ren-luyen-su-ben-bi-tron-tranh-that-bai-bang-cac-lieu-dopamine-re-tien-porn-mxh-game-de-sinh-ton-nam-gioi-phai-dinh-nghia-lai-su-nam-tinh-podcast.webp",
        "1m-dollar-content-strategy-any-business-podcast.html": "https://media.fedu.vn/k_covers/1m-dollar-content-strategy-any-business-podcast.webp",
        "met-moi-di-chuyen-xa-science.html": "https://media.fedu.vn/k_covers/met-moi-di-chuyen-xa-science.webp",
        "hinh-thanh-myelin-the-nao-science.html": "https://media.fedu.vn/k_covers/hinh-thanh-myelin-the-nao-science.webp",
        "dung-de-chiec-ghe-an-mon-tri-tue-cua-ban-science-long-form.html": "https://media.fedu.vn/k_covers/dung-de-chiec-ghe-an-mon-tri-tue-cua-ban-science-long-form.webp",
        "ky-nguyen-ai-tinh-nguoi-science.html": "https://media.fedu.vn/k_covers/ky-nguyen-ai-tinh-nguoi-science.webp",
        "dung-hy-sinh-su-can-bang-de-doi-lay-thanh-cong-podcast-science.html": "https://media.fedu.vn/k_covers/dung-hy-sinh-su-can-bang-de-doi-lay-thanh-cong-podcast-science.webp",
        "system-architecture-the-4-types-of-stress.html": "https://media.fedu.vn/k_covers/system-architecture-the-4-types-of-stress.webp",
        "sir-roger-penrose-giai-ma-khong-gian-y-thuc.html": "https://media.fedu.vn/k_covers/sir-roger-penrose-giai-ma-khong-gian-y-thuc.webp",
        "su-vo-nghia-ma-ban-dang-cam-thay-khong-phai-vi-ban-yeu-kem-ma-vi-ban-dang-dung-nao-trai-tu-duy-ky-thuat-thuat-toan-cuon-man-hinh-de-co-giai.html": "https://media.fedu.vn/k_covers/su-vo-nghia-ma-ban-dang-cam-thay-khong-phai-vi-ban-yeu-kem-ma-vi-ban-dang-dung-nao-trai-tu-duy-ky-thuat-thuat-toan-cuon-man-hinh-de-co-giai.webp",
        "system-9-the-biggest-ai-opportunity-is-missed.html": "https://media.fedu.vn/k_covers/system-9-the-biggest-ai-opportunity-is-missed.webp",
        "titlesu-that-ve-gan-nhiem-mo-tieu-duong-type-2-cach-chuyen-hoa-carbohydrate-thai-doc-co-the-va-dao-nguoc-benh-ly-bang-phuong-phap-low-carb.html": "https://media.fedu.vn/k_covers/titlesu-that-ve-gan-nhiem-mo-tieu-duong-type-2-cach-chuyen-hoa-carbohydrate-thai-doc-co-the-va-dao-nguoc-benh-ly-bang-phuong-phap-low-carb.webp",
        "20-gio-de-hoc-bat-cu-thu-gi-podcast.html": "https://media.fedu.vn/k_covers/20-gio-de-hoc-bat-cu-thu-gi-podcast.webp",
        "tu-bo-y-chi-bat-dau-tu-dong-hoa-khoi-tai-san-podcast.html": "https://media.fedu.vn/k_covers/tu-bo-y-chi-bat-dau-tu-dong-hoa-khoi-tai-san-podcast.webp",
        "so-tay-tu-duy-kien-tao-suc-manh-dich-thuc-podcast.html": "https://media.fedu.vn/k_covers/so-tay-tu-duy-kien-tao-suc-manh-dich-thuc-podcast.webp",
        "su-that-ve-ung-thu-nang-luong-te-bao-science.html": "https://media.fedu.vn/k_covers/su-that-ve-ung-thu-nang-luong-te-bao-science.webp",
        "su-that-ve-thuc-tai-la-kinh-vr-science-long-form.html": "https://media.fedu.vn/k_covers/su-that-ve-thuc-tai-la-kinh-vr-science-long-form.webp",
        "podcast-deepthink-05-science-podcast.html": "https://media.fedu.vn/k_covers/podcast-deepthink-05-science-podcast.webp",
        "truc-giac-chinh-la-thu-du-lieu-toc-do-cao-ma-ly-tri-chua-kip-giai-ma-podcast.html": "https://media.fedu.vn/k_covers/truc-giac-chinh-la-thu-du-lieu-toc-do-cao-ma-ly-tri-chua-kip-giai-ma-podcast.webp",
        "danh-thuc-tam-thuc-kien-tao-podcast.html": "https://media.fedu.vn/k_covers/danh-thuc-tam-thuc-kien-tao-podcast.webp",
        "lat-do-dinh-menh-khai-mo-tam-tri-podcast.html": "https://media.fedu.vn/k_covers/lat-do-dinh-menh-khai-mo-tam-tri-podcast.webp",
        "su-tai-sinh-cua-mot-huyen-thoai-busta-rhymes-science-long-form.html": "https://media.fedu.vn/k_covers/su-tai-sinh-cua-mot-huyen-thoai-busta-rhymes-science-long-form.webp",
        "stop-being-overlooked-become-famous-any-industry-podcast.html": "https://media.fedu.vn/k_covers/stop-being-overlooked-become-famous-any-industry-podcast.webp",
        "ta-luon-mac-dinh-rang-nhung-gi-minh-phat-ngon-ra-la-chinh-xac-nhung-gi-nguoi-kia-nghe-duoc-dieu-nay-la-sai-lam-podcast-science.html": "https://media.fedu.vn/k_covers/ta-luon-mac-dinh-rang-nhung-gi-minh-phat-ngon-ra-la-chinh-xac-nhung-gi-nguoi-kia-nghe-duoc-dieu-nay-la-sai-lam-podcast-science.webp",
        "spacex-ke-hoach-vi-dai-dua-sieu-may-tinh-ai-vao-vu-tru-chia-khoa-thang-hang-van-minh-nhan-loai-len-thang-kardashev-ii.html": "https://media.fedu.vn/k_covers/spacex-ke-hoach-vi-dai-dua-sieu-may-tinh-ai-vao-vu-tru-chia-khoa-thang-hang-van-minh-nhan-loai-len-thang-kardashev-ii.webp",
        "beo-phi-chi-la-trieu-chung-su-suy-yeu-cua-co-bap-moi-la-can-nguyen-podcast-science.html": "https://media.fedu.vn/k_covers/beo-phi-chi-la-trieu-chung-su-suy-yeu-cua-co-bap-moi-la-can-nguyen-podcast-science.webp",
        "dr-k-successful-people-broken-loneliness-ai-podcast.html": "https://media.fedu.vn/k_covers/dr-k-successful-people-broken-loneliness-ai-podcast.webp",
        "but-pha-gioi-han-ngung-ban-thoi-gian-lay-tien-bi-quyet-dong-goi-tri-tue-khai-thac-suc-manh-ai-de-xay-dung-co-may-in-tien-tu-dong-podcast.html": "https://media.fedu.vn/k_covers/but-pha-gioi-han-ngung-ban-thoi-gian-lay-tien-bi-quyet-dong-goi-tri-tue-khai-thac-suc-manh-ai-de-xay-dung-co-may-in-tien-tu-dong-podcast.webp",
        "giai-ma-trang-thai-flow-so-tay-thuc-chien-podcast.html": "https://media.fedu.vn/k_covers/giai-ma-trang-thai-flow-so-tay-thuc-chien-podcast.webp",
        "suc-khoe-tinh-duc-nghe-thuat-yeu-dr-rena-malik-science-long-form.html": "https://media.fedu.vn/k_covers/suc-khoe-tinh-duc-nghe-thuat-yeu-dr-rena-malik-science-long-form.webp",
        "new-way-to-win-on-youtube-podcast.html": "https://media.fedu.vn/k_covers/new-way-to-win-on-youtube-podcast.webp",
        "con-gian-ao-giac-binh-tinh-spiritual.html": "https://media.fedu.vn/k_covers/con-gian-ao-giac-binh-tinh-spiritual.webp",
        "elon-musk-10x-economy-podcast.html": "https://media.fedu.vn/k_covers/elon-musk-10x-economy-podcast.webp",
        "so-tay-but-pha-giai-ma-su-be-tac-science-long-form.html": "https://media.fedu.vn/k_covers/so-tay-but-pha-giai-ma-su-be-tac-science-long-form.webp",
        "thanh-cong-ruc-ro-khong-den-tu-su-may-man-ngau-nhien-ma-la-su-giao-thoa-khoc-liet-giua-noi-am-anh-muc-tieu-tot-do-kha-nang-tieu-hoa-su-choi-bo-va-viec-kien-dinh-bao-ve-ban-nga-giua-vong-vay-cua-du-luan-podcast-science.html": "https://media.fedu.vn/k_covers/thanh-cong-ruc-ro-khong-den-tu-su-may-man-ngau-nhien-ma-la-su-giao-thoa-khoc-liet-giua-noi-am-anh-muc-tieu-tot-do-kha-nang-tieu-hoa-su-choi-bo-va-viec-kien-dinh-bao-ve-ban-nga-giua-vong-vay-cua-du-luan-podcast-science.webp",
        "grow-business-part-time-100k-1m-podcast.html": "https://media.fedu.vn/k_covers/grow-business-part-time-100k-1m-podcast.webp",
        "co-che-chong-tai-virus-te-bao-guong-science.html": "https://media.fedu.vn/k_covers/co-che-chong-tai-virus-te-bao-guong-science.webp",
        "neu-chi-dung-ly-tri-khuyen-bao-ban-than-hay-quen-di-dieu-do-chang-khac-nao-dung-phan-mem-de-sua-mot-chiec-o-cung-bi-vo-vat-ly-chua-lanh-thuc-su-phai-bat-dau-tu-viec-day-co-the-cam-thay-an-toan-tro-lai-podcast-science.html": "https://media.fedu.vn/k_covers/neu-chi-dung-ly-tri-khuyen-bao-ban-than-hay-quen-di-dieu-do-chang-khac-nao-dung-phan-mem-de-sua-mot-chiec-o-cung-bi-vo-vat-ly-chua-lanh-thuc-su-phai-bat-dau-tu-viec-day-co-the-cam-thay-an-toan-tro-lai-podcast-science.webp",
        "vuot-qua-ma-tran-ban-nang-science.html": "https://media.fedu.vn/k_covers/vuot-qua-ma-tran-ban-nang-science.webp",
        "ai-matrix-override-system-architecture.html": "https://media.fedu.vn/k_covers/ai-matrix-override-system-architecture.webp",
        "elon-musk-va-su-menh-spacex-hanh-trinh-hien-thuc-hoa-giac-mo-dua-loai-nguoi-tro-thanh-nen-van-minh-da-hanh-tinh-va-khat-vong-chinh-phuc-vu.html": "https://media.fedu.vn/k_covers/elon-musk-va-su-menh-spacex-hanh-trinh-hien-thuc-hoa-giac-mo-dua-loai-nguoi-tro-thanh-nen-van-minh-da-hanh-tinh-va-khat-vong-chinh-phuc-vu.webp",
        "giam-can-thanh-cong-khong-den-tu-dong-luc-chop-nhoang-hay-mot-che-do-kieng-khem-than-thanh-no-la-qua-trinh-chap-nhan-su-that-khoa-hoc-calo.html": "https://media.fedu.vn/k_covers/giam-can-thanh-cong-khong-den-tu-dong-luc-chop-nhoang-hay-mot-che-do-kieng-khem-than-thanh-no-la-qua-trinh-chap-nhan-su-that-khoa-hoc-calo.webp",
        "hoi-tho-khong-chi-de-sinh-ton-do-la-bang-dieu-khien-cua-co-the-science-long-form.html": "https://media.fedu.vn/k_covers/hoi-tho-khong-chi-de-sinh-ton-do-la-bang-dieu-khien-cua-co-the-science-long-form.webp",
        "cam-bien-vat-ly-khac-de-quet-rac-bang-thong-science.html": "https://media.fedu.vn/k_covers/cam-bien-vat-ly-khac-de-quet-rac-bang-thong-science.webp",
        "giai-ma-su-phan-tam-science-long-form.html": "https://media.fedu.vn/k_covers/poster_237_fallback.webp",
        "phan-ung-tinh-duc-khac-biet-giua-hai-gioi.html": "https://media.fedu.vn/k_covers/poster_222_fallback.webp",
        "dr-ravinder-rice-wheat-anemia-nutrition-podcast.html": "https://media.fedu.vn/k_covers/poster_259.webp",
        "dr-bhaskar-rao-hospital-economics-healthcare-truth-podcast.html": "https://media.fedu.vn/k_covers/poster_225_fallback.webp",
        "he-qua-cua-bo-nao-bi-ngap-ngua-trong-rac-thai-te-bao-keto-science.html": "https://media.fedu.vn/k_covers/poster_183_fallback.webp",
        "use-ai-to-build-7-figure-personal-brand-podcast.html": "https://media.fedu.vn/k_covers/poster_164_1789663754755.webp",
        "sourav-ganguly-cricket-leadership-team-building-podcast.html": "https://media.fedu.vn/k_covers/poster_257.webp",
        "mark-bowden-body-language-trust-podcast.html": "https://media.fedu.vn/k_covers/poster_184_fallback.webp",
        "tram-giai-ma-tam-tri-kham-pha-ban-chat-cai-toi-podcast.html": "https://media.fedu.vn/k_covers/poster_213_fallback.webp",
        "ngu-20-phut-moi-3-tieng-science.html": "https://media.fedu.vn/k_covers/poster_165_1789663859473.webp",
        "tro-thanh-tinh-yeu-podcast.html": "https://media.fedu.vn/k_covers/poster_214_fallback.webp",
        "vuot-qua-nghich-canh-danh-thuc-truc-giac-loi-podcast.html": "https://media.fedu.vn/k_covers/poster_241_fallback.webp",
        "bieu-cam-ben-ngoai-va-cuong-che.html": "https://media.fedu.vn/k_covers/poster_191_fallback.webp",
        "giai-ma-tam-thuc-ky-nguyen-ky-di-podcast.html": "https://media.fedu.vn/k_covers/poster_196_fallback.webp",
        "giai-ma-matthew-mcconaughey-thiet-ke-trai-nghiem-hoc-tap-podcast-science.html": "https://media.fedu.vn/k_covers/poster_169_fallback.webp",
        "tinh-yeu-va-nhung-rac-roi-tam-ly-cua-ban-o-hien-tai-khong-phai-la-loi-do-dinh-menh-hay-su-xui-xeo-chung-chi-la-nhung-ban-sao-chep-vo-thuc.html": "https://media.fedu.vn/k_covers/poster_167_fallback.webp",
        "law-3-the-biggest-ai-opportunity-is-still-being-missed.html": "https://media.fedu.vn/k_covers/poster_85_1789663848434.webp",
        "ban-giao-huong-cua-su-song-kien-thuc-cot-loi-podcast.html": "https://media.fedu.vn/k_covers/poster_201_fallback.webp",
        "doi-khi-cach-duy-nhat-de-tai-sinh-mot-thu-vi-dai-la-dung-cam-de-no-chet-di-hoan-toan-dung-co-gang-va-viu-mot-he-thong-da-nat-hay-dap-bo-de.html": "https://media.fedu.vn/k_covers/poster_198_fallback.webp",
        "how-to-use-ai-first-and-win-podcast.html": "https://media.fedu.vn/k_covers/poster_206_fallback.webp",
        "vidita-vaidya-neuroscience-anxiety-addiction-podcast.html": "https://media.fedu.vn/k_covers/poster_224_fallback.webp",
        "ban-do-sinh-ton-qua-lang-kinh-cua-elon-musk-podcast.html": "https://media.fedu.vn/k_covers/poster_223_fallback.webp",
        "su-kien-tri-thuc-su-khong-phai-la-co-chap-lam-mot-thu-sai-lam-den-cung-podcast.html": "https://media.fedu.vn/k_covers/poster_236_fallback.webp",
        "system-1-why-i-believe-ai-has-already-surpassed-me.html": "https://media.fedu.vn/k_covers/poster_231_fallback.webp",
        "di-bo-5km-vs-ap-luc-nguc-bu-vai-u.html": "https://media.fedu.vn/k_covers/poster_168_fallback.webp",
        "toi-uu-ram-nho-04-nhom-3-phanh-khan-cap-science.html": "https://media.fedu.vn/k_covers/poster_197_fallback.webp",
        "co-che-tat-nao-khi-bi-kich-thich.html": "https://media.fedu.vn/k_covers/poster_190_fallback.webp",
        "the-1-ai-matrix-unmasking-the-game-podcast.html": "https://media.fedu.vn/k_covers/poster_200_fallback.webp",
        "antigravity-master-vault-guide.html": "https://media.fedu.vn/k_covers/poster_185_fallback.webp",
        "goc-nhin-vu-tru-podcast.html": "https://media.fedu.vn/k_covers/poster_240_fallback.webp",
        "ky-luat-la-he-thong-khong-phai-y-chi-science.html": "https://media.fedu.vn/k_covers/poster_215_fallback.webp",
        "danh-thuc-truc-giac-landing-page-podcast.html": "https://media.fedu.vn/k_covers/poster_212_fallback.webp",
        "new-way-to-market-business-with-ads-podcast.html": "https://media.fedu.vn/k_covers/poster_188_fallback.webp",
        "nghe-thuat-quyen-ru-va-ky-luat-vuon-toi-su-tinh-thong-science.html": "https://media.fedu.vn/k_covers/poster_177_fallback.webp",
        "giai-ma-nghe-thuat-ai-animation-lam-chu-quy-trinh-sang-tao-video-hoat-hinh-trieu-view-tu-con-so-0-de-thong-tri-kenh-ngach-mang-xa-hoi-ky.html": "https://media.fedu.vn/k_covers/poster_170_fallback.webp",
        "lanh-dao-tu-trai-tim-danh-thuc-suc-manh-noi-tai-podcast.html": "https://media.fedu.vn/k_covers/poster_218_fallback.webp",
        "masterclass-bi-mat-creatine-dr-darren-candow.html": "https://media.fedu.vn/k_covers/poster_270.webp",
        "su-be-tac-khong-den-tu-viec-ban-thieu-nang-luc-hay-luoi-bieng-no-xay-ra-khi-ban-bi-kich-thich-qua-muc-boi-thong-tin-nhieu-loan-va-dang-co-gang-giai-quyet-van-de-bang-phep-cong-podcast.html": "https://media.fedu.vn/k_covers/poster_264_severance.webp",
        "system-8-ai-has-no-polarity.html": "https://media.fedu.vn/k_covers/poster_258_ice_age.webp",
        "system-5-ai-has-no-polarity-we-decide-what-it-becomes.html": "https://media.fedu.vn/k_covers/poster_265_kill_la_kill.webp",
        "luat-choi-cua-ke-san-moi-su-thuc-tinh-tu-trong-hang-dong-science-long-form.html": "https://media.fedu.vn/k_covers/poster_271_quy_cau.webp",
        "nghe-thuat-tinh-tam-hien-dien-podcast.html": "https://media.fedu.vn/k_covers/poster_267_vi.webp",
        "fake-podcast-hieu-qua-va-kha-thi-cho-thuong-hieu-ca-nhan.html": "https://media.fedu.vn/k_covers/poster_272_ozark.webp",
        "dopamine-khong-chi-la-phan-thuong-no-la-cong-cu-can-bang-cang-ep-nao-nhan-nhieu-khoai-lac-gia-re-no-cang-tu-trung-phat-podcast.html": "https://media.fedu.vn/k_covers/poster_266_lion_king.webp",
        "ao-giac-nang-luc-khoa-hoc-cua-su-thuc-hanh-podcast-science.html": "https://media.fedu.vn/k_covers/poster_352_silicon_valley.webp",
        "sandeep-das-modern-dating-ai-marriage-podcast.html": "https://media.fedu.vn/k_covers/poster_229_fallback.webp",
        "sam-altman-lam-the-nao-de-chien-thang-khi-ai-thay-doi-moi-thu-podcast.html": "https://media.fedu.vn/k_covers/poster_269.webp",
        "the-speaking-coach-podcast.html": "https://media.fedu.vn/k_covers/poster_276_itaewon_class.webp",
        "tuong-lai-thuoc-ve-nhung-ai-biet-cuoi-len-lan-song-du-thua-cua-nang-luong-tinh-toan-compute-ai-va-khong-gian-de-lien-tuc-tien-hoa-podcast.html": "https://media.fedu.vn/k_covers/poster_277_1789612731209.webp",
        "gaurav-mehta-luxury-watchmaking-business-podcast.html": "https://media.fedu.vn/k_covers/poster_171_fallback.webp",
        "claude-motion-design.html": "https://media.fedu.vn/k_covers/poster_176_fallback.webp",
        "van-dong-tri-nao-science-long-form.html": "https://media.fedu.vn/k_covers/poster_189_fallback.webp",
        "ketosis-ai-talk-science-long-form.html": "https://media.fedu.vn/k_covers/poster_219_fallback.webp",
        "tu-tam-tri-den-trai-tim-so-tay-khai-van-science-long-form.html": "https://media.fedu.vn/k_covers/poster_166_1789663870559.webp",
        "danh-thuc-tri-nho-hoan-hao-science-long-form.html": "https://media.fedu.vn/k_covers/poster_273_fate_stay_night.webp",
        "4-ky-thuat-hack-nao-chong-phan-tan-zero-willpower-khong-dung-y-chi.html": "https://media.fedu.vn/k_covers/poster_261_made_in_abyss.webp",
        "y-thuc-dieu-khien-co-the-khong.html": "https://media.fedu.vn/k_covers/poster_249.webp",
        "toi-uu-luu-tru-thong-tin-science.html": "https://media.fedu.vn/k_covers/poster_228_fallback.webp",
        "bai-viet-moi-tu-youtube.html": "https://media.fedu.vn/k_covers/poster_274_kim_possible.webp",
        "mat-ma-tinh-lang-landing-page-podcast.html": "https://media.fedu.vn/k_covers/poster_248.webp",
        "doanh-nghiep-mot-nguoi-sieu-viet-ke-thang-la-nguoi-biet-dung-don-bay-may-moc-podcast.html": "https://media.fedu.vn/k_covers/poster_209_fallback.webp",
        "performance-10-the-real-danger-of-ai.html": "https://media.fedu.vn/k_covers/poster_351_co_hau_gai.webp",
        "giai-ma-nhu-cau-nguyen-thuy-cua-co-the.html": "https://media.fedu.vn/k_covers/poster_199_fallback.webp",
        "du-an-manhattan-cua-tri-tue-nhan-tao-podcast.html": "https://media.fedu.vn/k_covers/poster_251.webp",
        "alok-sama-money-trap-softbank-wealth-podcast.html": "https://media.fedu.vn/k_covers/poster_245.webp",
        "ky-nguyen-gpt-5-gpt-6-v-ai-khong-con-la-cuon-bach-khoa-toan-thu-de-chung-ta-tra-cuu.html": "https://media.fedu.vn/k_covers/poster_244.webp",
        "giai-ma-ton-thuong-chua-lanh-moi-quan-he-podcast.html": "https://media.fedu.vn/k_covers/poster_250.webp",
        "nao-bo-dang-dan-ta-di-lac-podcast.html": "https://media.fedu.vn/k_covers/poster_275_chi_chi_em_em.webp",
        "sauvik-banerjjee-cto-growth-mindset-podcast.html": "https://media.fedu.vn/k_covers/poster_174_fallback.webp",
        "sang-tao-tu-chan-science.html": "https://media.fedu.vn/k_covers/poster_173_fallback.webp",
        "mo-gawdat-system-analysis.html": "https://media.fedu.vn/k_covers/poster_246.webp",
        "youtube-b2b-jake-trinder-podcast.html": "https://media.fedu.vn/k_covers/poster_252.webp",
        "su-can-dam-thuc-su-khong-phai-la-nham-mat-lam-lieu-hay-khong-biet-so-do-la-ket-qua-cua-mot-qua-trinh-chuan-bi-ti-mi-den-muc-cuc-doan-podcast-science.html": "https://media.fedu.vn/k_covers/poster_253.webp",
        "lam-chu-tro-choi-tien-bac-ma-khong-can-y-chi-podcast.html": "https://media.fedu.vn/k_covers/poster_247.webp",
        "ai-system-architect-the-irreversible-gap.html": "https://media.fedu.vn/k_covers/poster_238_fallback.webp",
        "genius-personal-brand-advice-entrepreneurs-podcast.html": "https://media.fedu.vn/k_covers/poster_172_fallback.webp",
        "hired-therapist-grow-business-mindset-podcast.html": "https://media.fedu.vn/k_covers/poster_175_fallback.webp",
        "tinh-duc-vien-man-khong-phai-la-mot-phep-mau-tu-nhien-roi-xuong-dau-ban-no-la-ket-qua-cua-viec-xay-dung-von-tinh-duc-sexual-currency-hang.html": "https://media.fedu.vn/k_covers/poster_256_mad_men.webp",
        "srini-sriniwasan-ultra-rich-private-equity-wealth-podcast.html": "https://media.fedu.vn/k_covers/poster_208_fallback.webp",
        "puneet-nanda-walmart-retail-brand-scale-podcast.html": "https://media.fedu.vn/k_covers/poster_239_fallback.webp",
        "su-binh-yen-va-viec-thau-hieu-ban-than-moi-chinh-la-coi-nguon-cua-mot-suc-manh-sang-tao-ben-vung-nhat-podcast-science.html": "https://media.fedu.vn/k_covers/poster_268_dexter.webp",
        "su-that-ve-17-phuong-phap-cai-thien-lo-au-tu-bo-duong-tat-podcast-science.html": "https://media.fedu.vn/k_covers/poster_254.webp",
        "thiet-ke-lai-ban-the-dr-lisa-feldman-barrett-science-long-form.html": "https://media.fedu.vn/k_covers/poster_255.webp",
        "law-7-ai-made-iq-and-eq-accessible.html": "https://media.fedu.vn/k_covers/poster_350_turning_red.webp",
        "thoat-bay-content-creator-kien-tao-founder-brand-podcast.html": "https://media.fedu.vn/k_covers/poster_221_fallback.webp",
        "viec-hoc-bay-thuc-an-nhanh-tri-thuc-science.html": "https://media.fedu.vn/k_covers/poster_226_fallback.webp",
        "kichbanoffline-06-khi-nguoi-co-nghe-tu-tua-vao-huu-xa-tu-nhien-huong.html": "https://media.fedu.vn/k_covers/poster_260_halt_and_catch_fire.webp",
        "kichbanoffline-02-bay-chao-hoi-3-giay-dau.html": "https://media.fedu.vn/k_covers/poster_163_1789663742029.webp",
        "nghich-ly-cua-su-kiem-soat-science.html": "https://media.fedu.vn/k_covers/poster_233_fallback.webp",
        "suc-manh-cua-su-gioi-han-david-epstein-science-long-form.html": "https://media.fedu.vn/k_covers/poster_293_1789613273938.webp",
        "saurabh-mukherjea-middle-class-loan-trap-investing-podcast.html": "https://media.fedu.vn/k_covers/poster_234_fallback.webp",
        "insulin-la-chua-te-cua-chuyen-hoa.html": "https://media.fedu.vn/k_covers/poster_202_fallback.webp",
        "lam-chu-tai-chinh-khong-phai-la-cat-giam-nhung-ly-ca-phe-3-ma-la-kien-tao-mot-tam-nhin-cuoc-song-phong-phu-rich-life-vision-hop-nhat-tai-chinh-va-tu-dong-hoa-he-thong-dau-tu-de-tan-huong-dong-tien-mot-cach-khong-hoi-loi-podcast-science.html": "https://media.fedu.vn/k_covers/poster_205_fallback.webp",
        "hen-gio-nghe-thuat-toi-uu-hoa-ram-bo-nao.html": "https://media.fedu.vn/k_covers/poster_262_chicken_run.webp",
        "anahat-singh-squash-champion-mindset-podcast.html": "https://media.fedu.vn/k_covers/poster_192_fallback.webp",
        "giai-ma-trat-tu-the-gioi-nguyen-ly-quyet-dinh-ky-nguyen-moi-science.html": "https://media.fedu.vn/k_covers/poster_195_fallback.webp",
        "ban-chat-cua-thanh-cong-science.html": "https://media.fedu.vn/k_covers/poster_210_fallback.webp",
        "10-nam-cuoi-doi-podcast.html": "https://media.fedu.vn/k_covers/poster_217_fallback.webp",
        "masterclass-giai-ma-thuat-toan-xay-kenh-niche-podcast.html": "https://media.fedu.vn/k_covers/poster_242_fallback.webp",
        "giai-ma-tri-tue-trieu-do-don-bay-ky-luat-loi-chao-hang.html": "https://media.fedu.vn/k_covers/poster_180_fallback.webp",
        "tam-nhin-elon-musk-cuoc-chien-ve-nang-luong-vat-ly-va-nang-luc-san-xuat-podcast.html": "https://media.fedu.vn/k_covers/poster_178_fallback.webp",
        "nang-luong-song-qua-quan-sat-spiritual-science.html": "https://media.fedu.vn/k_covers/poster_187_fallback.webp",
        "vaibhav-sisinty-ai-second-brain-podcast.html": "https://media.fedu.vn/k_covers/poster_235_fallback.webp",
        "thuat-toan-dong-tab-lo-au-giai-phong-ram-nao-bo-book-typo.html": "https://media.fedu.vn/k_covers/poster_232_fallback.webp",
        "thuyet-phuc-khong-phai-la-cai-thang-nguoi-khac-ma-la-tao-ra-mot-con-duong-lot-tham-do-de-ho-tu-nguyen-buoc-den-muc-tieu-ma-ban-mong-muon-podcast.html": "https://media.fedu.vn/k_covers/poster_263_that_son_tam_linh.webp",
        "richard-teng-binance-crypto-future-of-money-podcast.html": "https://media.fedu.vn/k_covers/poster_294_1789613286524.webp",
        "nghien-cuu-doi-thu-mat-nang-luong.html": "https://media.fedu.vn/k_covers/poster_227_fallback.webp",
        "4-du-bao-ai-mo-gawdat-chuyen-giao-quyen-luc-podcast.html": "https://media.fedu.vn/k_covers/poster_220_fallback.webp",
        "17-phut-luyen-youtube-dot-pha-doanh-thu-jake-trinder-podcast.html": "https://media.fedu.vn/k_covers/poster_243_fallback.webp",
        "noi-so-hinh-anh-script.html": "https://media.fedu.vn/k_covers/poster_216_fallback.webp",
        "nghe-thuat-kiem-soat-cuoc-hoi-thoai-den-toi-podcast.html": "https://media.fedu.vn/k_covers/poster_211_fallback.webp",
        "su-that-ve-khung-hoang-nam-gioi-tre-scott-galloway-science-long-form.html": "https://media.fedu.vn/k_covers/poster_186_fallback.webp",
        "chris-williamson-champion-mindset-discipline-podcast.html": "https://media.fedu.vn/k_covers/poster_179_fallback.webp",
        "chia-khoa-giai-phong-dua-tre-ben-trong-garrain-jones.html": "https://media.fedu.vn/k_covers/poster_181_fallback.webp",
        "thien-dinh-nhu-mot-trang-thai-than-kinh-hoc.html": "https://media.fedu.vn/k_covers/poster_204_fallback.webp",
        "bi-an-tuoi-tho-nhin-an-science-long-form.html": "https://media.fedu.vn/k_covers/poster_203_fallback.webp",
        "performance-6-ai-is-starting-the-biggest-replacement-cycle-ever.html": "https://media.fedu.vn/k_covers/poster_194_fallback.webp",
        "ram-dopamin-re-tien-science.html": "https://media.fedu.vn/k_covers/poster_193_fallback.webp",
        "boc-tran-cu-lua-diet-vong.html": "https://media.fedu.vn/k_covers/poster_1.webp",
        "banner-phan-tich-2-mau-poster-tatler-va-ket-qua-hinh-anh.html": "https://media.fedu.vn/k_covers/poster_2.webp",
        "kichbanoffline-phau-thuat-kich-ban-5.html": "https://media.fedu.vn/k_covers/poster_3.webp",
        "kichbanoffline-phau-thuat-kich-ban-4.html": "https://media.fedu.vn/k_covers/poster_4.webp",
        "kichbanoffline-phau-thuat-kich-ban-3.html": "https://media.fedu.vn/k_covers/poster_5.webp",
        "banner-kho-120-mau-banner-face-dna-fluid-smart-grid-special-fx.html": "https://media.fedu.vn/k_covers/banner_kho_120_1789678629746.webp",
        "Bill_Ackman_Full_Tap_Ho_So.html": "https://media.fedu.vn/k_covers/bill_ackman_full_1789678674174.webp",
        "dom.html": "https://media.fedu.vn/k_covers/dom_1789678680800.webp",
        "tam-tri-den-dia-thuc-an-science-long-form.html": "https://media.fedu.vn/k_covers/poster_w1_13.webp",
        "cuoc-song-la-mot-vu-dieu-mong-manh-giua-su-an-toan-trat-tu-va-cai-chua-biet-hon-don-thay-vi-lan-tranh-kho-dau-viec-tu-nguyen-om-lay-podcast-science.html": "https://media.fedu.vn/k_covers/poster_w1_14.webp",
        "giai-ma-tam-ly-ai-ky-dr-ramani-science-long-form.html": "https://media.fedu.vn/k_covers/poster_w1_15.webp",
        "thoat-khoi-vong-lap-lo-au-bang-suc-manh-cua-ban-cau-nao-pha-podcast-science.html": "https://media.fedu.vn/k_covers/poster_w1_16.webp",
        "suc-manh-am-thanh-chua-lanh-learning-experience-podcast.html": "https://media.fedu.vn/k_covers/poster_w1_17.webp",
        "xu-ly-suy-nghi-chua-hoan-thanh-science.html": "https://media.fedu.vn/k_covers/poster_w1_18.webp",
        "man-hinh-ky-thuat-so-loi-song-tri-tre-dang-pha-huy-nao-bo-ra-sao-science-long-form.html": "https://media.fedu.vn/k_covers/poster_w1_19.webp",
        "cach-kiem-hang-trieu-do-tu-nhung-noi-dung-nham-chan.html": "https://media.fedu.vn/k_covers/poster_w1_20.webp",
        "su-thuc-tinh-cua-ong-trum-giai-tri-science.html": "https://media.fedu.vn/k_covers/poster_w1_21.webp",
        "kichbanoffline-04-view-dai-tra-vs-don-that.html": "https://media.fedu.vn/k_covers/poster_w1_22.webp",
        "lam-chu-nhip-sinh-hoc-intermittent-fasting-su-that-khoa-hoc-ve-tai-tao-te-bao-dot-mo-ky-luat-va-toi-uu-nang-luong-khong-can-dem-calo-khac.html": "https://media.fedu.vn/k_covers/poster_w1_23.webp",
        "so-tay-co-van-danh-thuc-truc-giac-lam-chu-cuoc-doi-science-long-form.html": "https://media.fedu.vn/k_covers/poster_w1_24.webp",
        "podcast-deepthink-04-science-podcast.html": "https://media.fedu.vn/k_covers/poster_w1_25.webp",
        "giai-ma-nao-bo-nguoi-cha-darby-saxbe-podcast.html": "https://media.fedu.vn/k_covers/poster_w1_26.webp",
        "lieu-thuoc-giai-doc-cho-tam-tri-su-tri-hoan-podcast.html": "https://media.fedu.vn/k_covers/poster_w1_27.webp",
        "new-way-to-monetize-your-content-online-podcast.html": "https://media.fedu.vn/k_covers/kieu_poster_28_1789842754029.webp",
        "hanh-phuc-tang-thap.html": "https://media.fedu.vn/k_covers/kingdom_poster_29_1789842768703.webp",
        "chung-ta-khong-khao-khat-quyen-luc-danh-vong-hay-vat-chat-thu-ta-thuc-su-cao-xe-tim-kiem-la-cam-giac-duoc-ket-noi-va-duoc-phep-ton-tai-moi.html": "https://media.fedu.vn/k_covers/bleach_poster_30_1789842777873.webp",
        "so-tay-thuc-chien-range-generalists-triumph-science-long-form.html": "https://media.fedu.vn/k_covers/missing_link_poster_31_1789842789119.webp",
        "ngung-do-loi-cho-cac-vi-sao-sadhguru-spiritual.html": "https://media.fedu.vn/k_covers/em_chua_18_poster_32_1789842800332.webp",
        "thoat-khoi-bay-logic-cham-den-tri-thong-minh-vu-tru-podcast.html": "https://media.fedu.vn/k_covers/jessica_jones_poster_33_1789842838674.webp",
        "su-giau-co-khong-den-tu-viec-tim-kiem-mot-van-cuoc-doi-doi-hay-theo-duoi-dam-me-mu-quang-no-la-ket-qua-cua-mot-qua-trinh-cuc-ky-nham-chan-podcast-science.html": "https://media.fedu.vn/k_covers/dr_stone_poster_34_1789842851911.webp",
        "khoa-hoc-giam-mo-tang-co-science.html": "https://media.fedu.vn/k_covers/the_good_dinosaur_poster_35_1789842867265.webp",
        "chung-ta-dang-dau-kho-vi-co-nhet-mot-nguoi-binh-thuong-vao-khuon-mau-cua-mot-vi-than-de-khoa-lap-moi-nhu-cau-tam-ly-hay-go-bo-lop-filter-ao.html": "https://media.fedu.vn/k_covers/hellbound_poster_36_1789842879179.webp",
        "scale-doanh-nghiep-voi-ai-data-the-2026-blueprint-podcast.html": "https://media.fedu.vn/k_covers/trang_ti_poster_37_1789842889125.webp",
        "law-6-the-90-second-rule.html": "https://media.fedu.vn/k_covers/mr_robot_poster_38_1789842938655.webp",
        "thuat-toan-mang-xa-hoi-khong-uu-ai-noi-dung-dep-no-uu-ai-su-giu-chan-retention-ban-khong-can-trieu-view-de-tu-do-tai-chinh-ban-chi-can-mot-ngach-nho-micro-niche-voi-tep-khan-gia-trung-thanh-san-sang-chi-tien-podcast-science.html": "https://media.fedu.vn/k_covers/anohana_poster_39_1789842949392.webp",
        "elon-musk-va-joe-rogan-ky-nguyen-thu-nhap-cao-toan-dan-nhung-chi-khi-chung-ta-don-sach-duoc-vi-rut-tam-tri-podcast.html": "https://media.fedu.vn/k_covers/a_bugs_life_poster_40_1789842961645.webp",
        "tai-sao-nguoi-hoc-rong-lai-thang-trong-the-gioi-chuyen-mon-hoa-podcast-science.html": "https://media.fedu.vn/k_covers/dao_doc_dac_poster_41_1789842976271.webp",
        "no-luc-ket-noi-cuc-ky-nho-be-mot-cau-noi-mot-cai-cham-mot-anh-nhin-science-long-form.html": "https://media.fedu.vn/k_covers/band_of_brothers_poster_42_1789842986864.webp",
        "ai-system-analysis-limits-crossed.html": "https://media.fedu.vn/k_covers/dragon_ball_poster_43_1789843073907.webp",
        "tu-duy-ranh-mach-cua-sam-altman-podcast.html": "https://media.fedu.vn/k_covers/frankenweenie_poster_44_1789843084739.webp",
        "ai-survival-playbook-the-2030-deadline-spiritual.html": "https://media.fedu.vn/k_covers/gai_gia_lam_chieu_poster_45_1789843095094.webp",
        "nao-bo-dang-lua-doi-ban-podcast.html": "https://media.fedu.vn/k_covers/doom_patrol_poster_46_1789843111084.webp",
        "nghe-thuat-buong-bo-ap-luc-thanh-cong-podcast-science.html": "https://media.fedu.vn/k_covers/record_of_ragnarok_poster_47_1789843124853.webp",
        "giai-ma-giac-ngu-mentors-playbook-podcast.html": "https://media.fedu.vn/k_covers/robots_poster_48_1789843269488.webp",
        "performance-8-the-4-types-of-stress.html": "https://media.fedu.vn/k_covers/scandal_poster_49_1789843280286.webp",
        "5-cong-thuc-pho-bien-cho-thuong-hieu-ca-nhan.html": "https://media.fedu.vn/k_covers/altered_carbon_poster_50_1789843289176.webp",
        "duong-ruot-khong-don-thuan-la-co-may-tieu-hoa-thuc-an-no-la-bo-nao-thu-hai-va-la-trung-tam-dieu-khien-70-he-mien-dich-cua-ban-viem-nhiem.html": "https://media.fedu.vn/k_covers/sailor_moon_poster_51_1789843298663.webp",
        "kichbanoffline-07-dong-goi-bai-tu-van-thanh-video-1-phut.html": "https://media.fedu.vn/k_covers/ben_10_poster_52_1789843309941.webp",
        "gioi-han-cua-su-kiem-soat-podcast.html": "https://media.fedu.vn/k_covers/gioi-han-cua-su-kiem-soat-podcast.webp",
        "con-duong-don-gian-toi-cua-cai-science.html": "https://media.fedu.vn/k_covers/con-duong-don-gian-toi-cua-cai-science.webp",
        "lam-chu-duong-huyet-podcast.html": "https://media.fedu.vn/k_covers/poster_30.webp",
        "ban-chat-cua-su-thao-tung-than-kinh-trong-ky-nguyen-so-science.html": "https://media.fedu.vn/k_covers/poster_31.webp",
        "suc-manh-chua-lanh-tu-tra-dao-trung-hoa-co-dai-kham-pha-nghe-thuat-song-cham-ket-noi-tam-hon-va-trai-nghiem-thuc-tinh-chachi-cung-co-van.html": "https://media.fedu.vn/k_covers/poster_32.webp",
        "ban-nga-su-gan-ket-nhan-thuc-trai-nghiem-hoc-tap-podcast-science.html": "https://media.fedu.vn/k_covers/cover_127.webp",
        "neu-de-lich-thientap-gym-vao-buoi-toi-ban-se-mat-12-tieng-ban-ngay-thinh-thoang-nho-lai-no-voi-cam-giac-nang-ne-lam-no-luc-7h-sang-ban-co.html": "https://media.fedu.vn/k_covers/cover_128.webp",
        "ngu-quan-doi-co-ham-bao-dong-nao-dang-co-rac.html": "https://media.fedu.vn/k_covers/cover_129.webp",
        "ban-do-cau-truc-giac-ngu-science.html": "https://media.fedu.vn/k_covers/cover_130.webp",
        "kien-truc-co-the-tinh-te-podcast-science.html": "https://media.fedu.vn/k_covers/cover_131.webp",
        "dopamine-re-tien-01-science.html": "https://media.fedu.vn/k_covers/cover_132.webp",
        "masterclass-lam-giau-khong-nho-may-man-naval-ravikant-podcast.html": "https://media.fedu.vn/k_covers/cover_133.webp",
        "giai-ma-ctmu-tam-tri-vu-tru-science-podcast.html": "https://media.fedu.vn/k_covers/cover_134.webp",
        "chung-ta-dang-tu-tao-ra-mot-the-gioi-qua-mong-manh-va-xa-la-so-voi-sinh-hoc-cua-chinh-minh-su-nguy-hiem-lon-nhat-khong-nam-o-ben-ngoai-ma-nam-o-toc-do-thay-doi-vuot-qua-kha-nang-thich-nghi-cua-nhan-loai-podcast-science.html": "https://media.fedu.vn/k_covers/cover_135.webp",
        "11-years-content-creation-what-actually-works-podcast.html": "https://media.fedu.vn/k_covers/cover_139.webp",
        "how-to-get-your-personal-brand-unstuck-podcast.html": "https://media.fedu.vn/k_covers/cover_140.webp",
        "du-doan-va-quan-ly-ngan-sach-nang-luong-cua-co-the-science.html": "https://media.fedu.vn/k_covers/poster_53.webp",
        "khoa-hoc-nao-bo-10x-tap-trung-va-tri-nho-dr-sahar-yousef-podcast.html": "https://media.fedu.vn/k_covers/poster_54.webp",
        "giai-ma-hoi-rosicrucian-kien-truc-hoa-nang-luong-thuc-tinh-tam-linh.html": "https://media.fedu.vn/k_covers/poster_55.webp",
        "phan-tich-ngon-ngu-co-the-va-truc-giac.html": "https://media.fedu.vn/k_covers/poster_56.webp",
        "adhd-roi-loan-tang-dong-giam-chu-y-podcast-science.html": "https://media.fedu.vn/k_covers/poster_57.webp",
        "performance-7-most-stress-comes-from-this-one-mistake.html": "https://media.fedu.vn/k_covers/poster_58.webp",
        "tu-do-tai-chinh-lo-trinh-thuc-chien-de-lam-chu-dong-tien-thoat-khoi-vong-xoay-com-ao-gao-tien-va-xay-dung-di-san-ben-vung-trong-ky-nguyen.html": "https://media.fedu.vn/k_covers/poster_59.webp",
        "ban-nghi-rang-con-nguoi-sinh-ra-da-co-ban-tinh-tot-dep-va-minh-bach-sai-lam-chung-ta-deu-la-nhung-dien-vien-bam-sinh-mang-trong-minh-mot.html": "https://media.fedu.vn/k_covers/poster_60.webp",
        "ai-changed-marketing-forever-agencies-dead-podcast.html": "https://media.fedu.vn/k_covers/poster_fix_gundam.webp",
        "su-doi-tra-ve-phat-trien-ban-than-podcast-science.html": "https://media.fedu.vn/k_covers/poster_62.webp",
        "giai-phong-chan-nga-ban-do-thuc-tinh-chua-lanh-tam-thuc.html": "https://media.fedu.vn/k_covers/poster_fix_hai_phuong.webp",
        "lam-chu-ngon-tu-khong-nam-o-viec-gianh-phan-thang.html": "https://media.fedu.vn/k_covers/poster_fix_stranger_things.webp",
        "thanh-cong-kinh-doanh-khong-dinh-hinh-tu-viec-ban-gioi-moi-thu-ma-tu-viec-ban-ru-bo-cai-toi-am-anh-voi-chat-luong-va-muon-suc-nhung-khoi-oc.html": "https://media.fedu.vn/k_covers/poster_fix_how_to_train_your_dragon.webp",
        "so-tay-chuyen-hoa-the-best-advice-from-this-year-podcast-science.html": "https://media.fedu.vn/k_covers/poster_66.webp",
        "y-nghia-cuoc-song-khong-nam-o-viec-dung-nao-trai-de-giai-quyet-moi-rac-roi-nhu-mot-co-may-ma-la-danh-thuc-nao-phai-de-can-dam-hoi-nhung-cau.html": "https://media.fedu.vn/k_covers/poster_67.webp",
        "moi-ngay-co-the-mac-10000-loi-dna-ung-thu-vi-mo-ban-khong-chet-vi-chung-la-do-he-thong-phong-thu-tu-nhien-luon-tuc-truc-dung-nap-thuc-pham-de-nuoi-benh-podcast.html": "https://media.fedu.vn/k_covers/poster_68.webp",
        "do-la-ngon-ngu-cua-mot-he-noi-tiet-dang-gao-thet-vi-mat-can-bang-podcast.html": "https://media.fedu.vn/k_covers/poster_69.webp",
        "toi-uu-ram-nho-01-science.html": "https://media.fedu.vn/k_covers/poster_70.webp",
        "day-su-bat-binh-dang-len-muc-cuc-doan.html": "https://media.fedu.vn/k_covers/poster_71.webp",
        "thieu-hut-vitamin-d-mang-lai-rui-ro-suc-khoe-nghiem-trong-podcast.html": "https://media.fedu.vn/k_covers/poster_72.webp",
        "ky-luat-de-tai-cau-truc-cuoc-doi-podcast.html": "https://media.fedu.vn/k_covers/poster_73.webp",
        "the-gioi-bi-thao-tung-boi-tri-tuong-tuong-podcast.html": "https://media.fedu.vn/k_covers/poster_74.webp",
        "mastering-communication-vinh-giang-podcast.html": "https://media.fedu.vn/k_covers/poster_75.webp",
        "su-lot-xac-thuc-su-khong-den-tu-viec-choi-bo-noi-dau-hay-ep-minh-vao-mot-khuon-mau-can-bang-moi-ngay-no-den-tu-viec-dam-dung-su-kho-chiu.html": "https://media.fedu.vn/k_covers/poster_76.webp",
        "buc-tranh-toan-canh-ve-suc-khoe-sinh-san-nam-gioi-science-long-form.html": "https://media.fedu.vn/k_covers/poster_77.webp",
        "chung-ta-dang-song-trong-nhung-co-may-sinh-hoc-duoc-thiet-ke-de-sinh-ton-trong-su-khac-nghiet-khan-hiem-va-van-dong-lien-tuc-khi-dat-co-may.html": "https://media.fedu.vn/k_covers/poster_78.webp",
        "hack-nao-bo-dr-daniel-amen-science.html": "https://media.fedu.vn/k_covers/poster_79.webp",
        "deeep-think-chu-nghia-khac-ky-sinh-hoc-biological-stoicism-podcast.html": "https://media.fedu.vn/k_covers/poster_80.webp",
        "bac-si-nhan-khoa-so-1-loi-noi-doi-ve-anh-sang-xanh-su-that-ve-ruoi-bay-podcast.html": "https://media.fedu.vn/k_covers/poster_81.webp",
        "lam-giau-khong-phai-la-mot-canh-bac-on-ao-do-la-mot-he-thong-ky-luat-nham-chan-den-kinh-ngac-podcast.html": "https://media.fedu.vn/k_covers/poster_82.webp",
        "ma-hoa-su-ben-bi-xay-dung-he-sinh-thai-loi-science.html": "https://media.fedu.vn/k_covers/poster_83.webp",
        "thuat-toan-thanh-that-va-cong-nghe-tan-nhiet-tam-thuc.html": "https://media.fedu.vn/k_covers/poster_84.webp",
        "co-dep-soleus-la-gi-va-tai-sao-no-dac-biet-science-podcast.html": "https://media.fedu.vn/k_covers/co-dep-soleus-la-gi-va-tai-sao-no-dac-biet-science-podcast.webp",
        "hanh-trinh-tu-ton-thuong-den-coi-nguon-suc-manh.html": "https://media.fedu.vn/k_covers/hanh-trinh-tu-ton-thuong-den-coi-nguon-suc-manh.webp",
        "tai-thiet-lap-nao-bo-ky-luat-ky-nguyen-so-science.html": "https://media.fedu.vn/k_covers/tai-thiet-lap-nao-bo-ky-luat-ky-nguyen-so-science.webp",
        "giai-ma-tien-loi-chet-nguoi-learning-landing-page-podcast.html": "https://media.fedu.vn/k_covers/poster_w1_1.webp",
        "lap-trinh-bo-nao-02-science.html": "https://media.fedu.vn/k_covers/poster_w1_2.webp",
        "gat-bo-noi-so-bi-danh-gia-sao-chep-y-het-nhung-mo-hinh-dang-hoat-dong-tot-o-noi-khac-va-lien-tuc-kiem-chung-y-tuong-re-tien-thong-qua-internet-podcast.html": "https://media.fedu.vn/k_covers/poster_w1_3.webp",
        "giai-ma-noi-co-don-ty-do-brian-chesky-learning-experience-science-long-form.html": "https://media.fedu.vn/k_covers/poster_w1_4.webp",
        "tamlyhoc.html": "https://media.fedu.vn/k_covers/poster_w1_5.webp",
        "lauren-tan-kien-truc-agentic-1000-pr-dune-xai-cursor-podcast.html": "https://media.fedu.vn/k_covers/poster_w1_6.webp",
        "tich-tru-ky-thuat-so-nguy-bien-suu-tam.html": "https://media.fedu.vn/k_covers/poster_w1_7.webp",
        "kien-tao-thuc-tai-learning-landing-page.html": "https://media.fedu.vn/k_covers/poster_w1_8.webp",
        "performance-9-ai-is-starting-replacement-cycle.html": "https://media.fedu.vn/k_covers/poster_w1_9.webp",
        "so-tay-mentor-peak-span-giai-ma-sinh-hoc-podcast.html": "https://media.fedu.vn/k_covers/poster_w1_10.webp",
        "y-thuc-khong-chi-la-mot-co-may-sinh-ton-no-la-khong-gian-tu-do-cuoi-cung-cua-con-nguoi-podcast-science.html": "https://media.fedu.vn/k_covers/poster_w1_11.webp",
        "system-6-artificial-intelligence-isnt-the-problem.html": "https://media.fedu.vn/k_covers/poster_w1_12.webp",
        "rajchannel.html": "https://media.fedu.vn/k_covers/rajchannel.webp",
        "logicxaykenh.html": "https://media.fedu.vn/k_covers/logicxaykenh.webp",
        "test-search.html": "https://media.fedu.vn/k_covers/test-search.webp",
        "logickenh-31-vo-boc-video-tao-lead-dich-vu-offline.html": "https://media.fedu.vn/k_covers/logickenh-31-vo-boc-video-tao-lead-dich-vu-offline.webp",
        "index.html": "https://media.fedu.vn/k_covers/index.webp",
        "logickenh-xaykenh.html": "https://media.fedu.vn/k_covers/logickenh-xaykenh.webp",
        "logicxaykenh-logic-xay-kenh-chuyen-gia.html": "https://media.fedu.vn/k_covers/logicxaykenh-logic-xay-kenh-chuyen-gia.webp",
        "logickenh.html": "https://media.fedu.vn/k_covers/logickenh.webp",
        "temp_template.html": "https://media.fedu.vn/k_covers/temp_template.webp",
        "algolia-test.html": "https://media.fedu.vn/k_covers/algolia-test.webp",
        "poster_audit_dashboard.html": "https://media.fedu.vn/k_covers/poster_audit_dashboard.webp",
        "10-thien-kien-tien-hoa-science.html": "https://media.fedu.vn/k_covers/poster_21_1789861219442.webp",
        "sovereignty-vitality-masterclass-podcast.html": "https://media.fedu.vn/k_covers/poster_22_1789861229588.webp",
        "giac-ngu-ngan-20-phut-science.html": "https://media.fedu.vn/k_covers/poster_23_1789861240061.webp",
        "de-che-tam-tri-cua-simon-cowell-science.html": "https://media.fedu.vn/k_covers/poster_24_1789861250289.webp",
        "kichbanoffline-phau-thuat-kich-ban-2.html": "poster_1_severance_1789861213029.jpg",
        "kichbanoffline-phau-thuat-kich-ban-1.html": "poster_2_kill_la_kill_1789861221590.jpg",
        "hanh-trinh-chua-lanh-nguyen-ban-podcast.html": "poster_3_the_lion_king_1789861231506.jpg",
        "vi-du-ve-thue-bang-thong-va-giam-iq-science.html": "poster_4_vi_1789861241605.jpg",
        "y-hoc-30-chu-dong-can-thiep-tu-som-coi-tap-luyen-la-loai-thuoc-manh-nhat-va-muc-tieu-la-keo-dai-tuoi-tho-khoe-manh-healthspan-thay-vi-chi.html": "https://media.fedu.vn/k_covers/poster_fix_rezero.webp",
        "khoi-nghiep-ky-nguyen-moi-science.html": "https://media.fedu.vn/k_covers/poster_fix_trang_quynh.webp",
        "hay-ngung-dua-vao-y-chi-hay-cam-tinh-de-ra-quyet-dinh-song-bang-cach-thiet-lap-thuat-toan-ky-luat-blueprint-va-de-du-lieu-len-tieng-ban-co.html": "https://media.fedu.vn/k_covers/poster_fix_money_heist.webp",
        "system-7-the-3-ways-pressure-breaks-you.html": "https://media.fedu.vn/k_covers/poster_fix_psychopass.webp",
    }

    for f in files:
        if f in exclude:
            continue
            
        filepath = os.path.join(os.getcwd(), f)
        stat = os.stat(filepath)
        try:
            mod_time = datetime.fromtimestamp(stat.st_birthtime).isoformat()
        except AttributeError:
            mod_time = datetime.fromtimestamp(stat.st_mtime).isoformat()
        
        with open(filepath, 'r', encoding='utf-8') as file:
            content = file.read()
            soup = BeautifulSoup(content, 'html.parser')
            title_tag = soup.find('title')
            title = title_tag.text.strip() if title_tag else f.replace('.html', '').replace('-', ' ').title()
            
            # Simple excerpt (first paragraph with text > 50 chars)
            excerpt = "Bài viết chuyên sâu từ kho dữ liệu Antigravity."
            for p in soup.find_all('p'):
                text = p.text.strip()
                if len(text) > 50:
                    excerpt = text[:150] + "..."
                    break
                    
            # Determine category based on filename keywords
            fname_lower = f.lower()
            if 'broll' in fname_lower or 'quay' in fname_lower:
                cat = "broll"
                cat_label = "🎬 B-Roll & Cảnh Trám"
            elif 'podcast' in fname_lower:
                cat = "science"
                cat_label = "🧠 Tâm Lý & Não Bộ"
            elif 'science' in fname_lower:
                cat = "science"
                cat_label = "🧠 Khoa Học"
            else:
                cat = "other"
                cat_label = "📌 Bài Viết"
                
        if f in cover_mapping:
            cover_img = cover_mapping[f]
        else:
            import hashlib
            fallback_images = [
                "https://media.fedu.vn/k_covers/poster_alien.webp",
                "https://media.fedu.vn/k_covers/poster_sekiro.webp",
                "https://media.fedu.vn/k_covers/poster_bicycle_thieves.webp",
                "https://media.fedu.vn/k_covers/poster_halo.webp",
                "https://media.fedu.vn/k_covers/poster_ghost_in_the_shell.webp",
                "https://media.fedu.vn/k_covers/poster_god_of_war.webp",
                "https://media.fedu.vn/k_covers/poster_children_of_heaven.webp",
                "https://media.fedu.vn/k_covers/poster_pulp_fiction.webp",
                "https://media.fedu.vn/k_covers/poster_v_for_vendetta_v2.webp",
                "https://media.fedu.vn/k_covers/poster_inglourious_basterds.webp",
                "https://media.fedu.vn/k_covers/poster_the_sting.webp",
                "https://media.fedu.vn/k_covers/poster_cowboy_bebop.webp",
                "https://media.fedu.vn/k_covers/poster_mass_effect.webp",
                "https://media.fedu.vn/k_covers/poster_doom.webp",
                "https://media.fedu.vn/k_covers/poster_forrest_gump.webp"
            ]
            idx = int(hashlib.md5(f.encode('utf-8')).hexdigest(), 16) % len(fallback_images)
            cover_img = fallback_images[idx]

        posts.append({
            "filename": f,
            "title": title,
            "excerpt": excerpt,
            "category_key": cat,
            "category_label": cat_label,
            "cover_image": cover_img,
            "updated_at": mod_time,
            "read_time": "5 phút đọc",
            "file_size_kb": round(stat.st_size / 1024)
        })

    # Sort by updated_at descending
    posts.sort(key=lambda x: x['updated_at'], reverse=True)

    with open('posts-manifest.json', 'w', encoding='utf-8') as out:
        json.dump({"posts": posts}, out, ensure_ascii=False, indent=2)
        
    print(f"Generated manifest with {len(posts)} posts.")

if __name__ == "__main__":
    generate()
