import json

with open('target_50_batch_4.json') as f:
    targets = json.load(f)

ideas = [
    ("The Empire Strikes Back (1980)", "empire_strikes_back", "Low angle looking up from Bespin carbon-freezing chamber platform. Holding ignited glowing blue lightsaber facing colossal looming silhouette of Darth Vader against industrial orange and teal mist. Typography text \"THE EMPIRE STRIKES BACK\". 9:16 vertical poster."),
    ("The Big Short (2015)", "big_short", "Medium shot in messy hedge fund office. Barefoot on desk, staring intensely at hand-drawn credit collapse diagrams on glass marker board in dim office lighting. Typography text \"THE BIG SHORT\". 9:16 vertical poster."),
    ("The Matrix Reloaded (2003)", "matrix_reloaded", "Action tracking shot on dark highway. Crouched forward riding black Ducati superbike at high speed, drawing dual katanas amidst motion-blurred city lights. Digital green typography text \"THE MATRIX RELOADED\". 9:16 vertical poster."),
    ("Pirates of the Caribbean: Dead Man's Chest (2006)", "pirates_dead_mans_chest", "Extreme wide shot from storm-battered ship deck. Holding cutlass defiantly as colossal Kraken tentacles wrap around mast amidst foaming white ocean spray. Weathered gold typography text \"DEAD MAN'S CHEST\". 9:16 vertical poster."),
    ("12 Angry Men (1957)", "twelve_angry_men", "Eye-level close-up in jury deliberation room. In white dress shirt soaked in sweat with loosened tie, stabbing switchblade knife into wooden table before eleven jurors in high-contrast black and white. Typography text \"12 ANGRY MEN\". 9:16 vertical poster."),
    ("Casablanca (1942)", "casablanca_1942", "Subtle Dutch angle at airport runway. In trench coat with turned-up collar and fedora, tipping brim in farewell amidst thick atmospheric airfield fog and searchlights. Flowing classic typography text \"Casablanca\". 9:16 vertical poster."),
    ("Lawrence of Arabia (1962)", "lawrence_of_arabia", "Extreme wide shot of vast desert horizon. Riding white camel across shimmering fiery red dunes of Nefud desert under blistering noon sun with heat distortion. Gilded classical typography text \"LAWRENCE OF ARABIA\". 9:16 vertical poster."),
    ("Citizen Kane (1941)", "citizen_kane", "Worm's-eye view from polished stone floor. Dropping glass snowglobe as it shatters before colossal roaring fireplace of Xanadu estate in dramatic chiaroscuro noir lighting. Chiseled typography text \"CITIZEN KANE\". 9:16 vertical poster."),
    ("Sunset Boulevard (1950)", "sunset_boulevard", "Looking up from deep bottom of luxury swimming pool. Floating face-down in calm turquoise water reflecting flashing red and blue police sirens at eerie twilight. Metal street-sign typography text \"SUNSET BLVD.\". 9:16 vertical poster."),
    ("The Third Man (1949)", "the_third_man", "Canted angle in Vienna brick sewer archway. Tall elongated shadow cast across wet mossy brick walls with narrow streetlamp beam piercing darkness. Slanted yellow typography text \"THE THIRD MAN\". 9:16 vertical poster."),
    ("North by Northwest (1959)", "north_by_northwest", "Wide high-angle shot in flat cornfield. Sprinting in tailored grey suit desperately fleeing vintage crop duster biplane swooping dangerously low under harsh sunlight. Architectural grid typography text \"NORTH BY NORTHWEST\". 9:16 vertical poster."),
    ("Dial M for Murder (1954)", "dial_m_for_murder", "Over-the-shoulder close-up in shadowy study. Clutching vintage brass telephone receiver beside heavy crimson velvet curtains under lone desk lamp beam. Blood-red typography text \"DIAL M FOR MURDER\". 9:16 vertical poster."),
    ("Chinatown (1974)", "chinatown_1974", "Medium close-up profile. Lighting a cigarette under beige fedora with white bandage taped across slashed nose against golden Los Angeles drought sunset. Vintage 1930s crimson typography text \"CHINATOWN\". 9:16 vertical poster."),
    ("L.A. Confidential (1997)", "la_confidential", "Low angle in police interrogation room. Holding snub-nosed .38 revolver and gleaming gold LAPD detective badge under harsh industrial overhead cone light. Stamped gold typography text \"L.A. CONFIDENTIAL\". 9:16 vertical poster."),
    ("The French Connection (1971)", "french_connection", "Tracking shot sprinting down gritty Brooklyn street. Wearing brown overcoat and pork pie hat underneath rusty elevated subway tracks in muddy slush. Gritty stencil typography text \"THE FRENCH CONNECTION\". 9:16 vertical poster."),
    ("Bullitt (1968)", "bullitt_1968", "Medium shot leaning against dark highland green Ford Mustang Fastback on steep San Francisco hill crest against bay fog at dusk. Bold neon typography text \"BULLITT\". 9:16 vertical poster."),
    ("Dirty Harry (1971)", "dirty_harry", "Extreme low angle looking up barrel of massive .44 Magnum revolver. Aiming steady hand in tweed sport coat and sunglasses in sunny city park. Bold crimson typography text \"DIRTY HARRY\". 9:16 vertical poster."),
    ("Lethal Weapon (1987)", "lethal_weapon", "Action freeze-frame in torrential downpour. Gripping Beretta 92FS with both hands, body caked in wet sand during beachside showdown illuminated by lightning. Metallic red typography text \"LETHAL WEAPON\". 9:16 vertical poster."),
    ("Point Break (1991)", "point_break", "Bird's-eye view freefalling through open sky. Arms spread wide skydiving without parachute, holding rubber ex-president mask against blazing Pacific ocean waves below. Cyan typography text \"POINT BREAK\". 9:16 vertical poster."),
    ("Bad Boys (1995)", "bad_boys_1995", "Slow-motion low angle running forward. Black silk shirt unbuttoned billowing in wind, dual pistols drawn before black sports car against fiery Miami sunset with palm trees. Chrome typography text \"BAD BOYS\". 9:16 vertical poster."),
    ("Mission: Impossible - Fallout (2018)", "mi_fallout", "Vertigo angle hanging from helicopter landing skid. Gripping metal bar with one hand over jagged snowy peaks of Kashmir amidst stormy clouds. Crisp typography text \"MISSION: IMPOSSIBLE - FALLOUT\". 9:16 vertical poster."),
    ("Casino (Opening) (1995)", "casino_opening", "Medium shot turning car ignition key. Giant fireball explosion detonating behind into midnight desert sky, launching body into glowing Vegas neon. Marquee bulb typography text \"CASINO\". 9:16 vertical poster."),
    ("Good Will Hunting (1997)", "good_will_hunting", "Symmetrical eye-level view down MIT hallway. Holding mop in janitor uniform, standing mesmerized before chalkboard filled with complex solved mathematical proof. Emerald typography text \"GOOD WILL HUNTING\". 9:16 vertical poster."),
    ("Dead Poets Society (1989)", "dead_poets_society", "Low angle looking up from classroom floor. Standing proudly atop wooden school desk in boarding school uniform, smiling defiantly into autumn window light. Gilded serif typography text \"DEAD POETS SOCIETY\". 9:16 vertical poster."),
    ("A Beautiful Mind (2001)", "beautiful_mind", "Silhouette through dormitory windowpane. Tracing complex geometric cryptography formulas in white chalk across glass looking out onto moonlit campus. Silver typography text \"A BEAUTIFUL MIND\". 9:16 vertical poster."),
    ("The Imitation Game (2014)", "imitation_game", "Wide shot inside Bletchley Park workshop. Hands adjusting bronze rotor drums and copper cables of giant clicking Bombe enigma machine in warm amber glow. Cryptic typography text \"THE IMITATION GAME\". 9:16 vertical poster."),
    ("Apollo 13 (1995)", "apollo_13", "Tight close-up inside freezing lunar module. Sweat and condensed water droplets on face, wearing NASA headset and holding duct-taped lithium hydroxide canister. Bold NASA typography text \"APOLLO 13\". 9:16 vertical poster."),
    ("First Man (2018)", "first_man", "Macro reflection on gold astronaut helmet visor. Capturing the solitary first human footprint in powdery grey lunar regolith under pitch-black deep space sky. Minimalist white typography text \"FIRST MAN\". 9:16 vertical poster."),
    ("Gravity (2013)", "gravity_2013", "Dutch angle tumbling in zero gravity. Untethered white spacesuit drifting helplessly against vibrant curving blue horizon of planet Earth. Widely spaced typography text \"GRAVITY\". 9:16 vertical poster."),
    ("The Martian (2015)", "the_martian", "Medium shot inside habitat greenhouse module. Kneeling gently holding vibrant green potato plant sprout in red Martian soil under grow lights against red landscape. Industrial orange typography text \"THE MARTIAN\". 9:16 vertical poster."),
    ("Sunshine (2007)", "sunshine_2007", "Total silhouette on observation deck. Standing before colossal golden heat shield gazing directly into blazing blinding corona of the Sun. Incandescent gold typography text \"SUNSHINE\". 9:16 vertical poster."),
    ("Moon (2009)", "moon_2009", "Low angle from dusty lunar surface looking up at rover. Sitting in driver cabin gazing through visor at Earth suspended in pitch-black starry sky. Crisp silver typography text \"MOON\". 9:16 vertical poster."),
    ("Oblivion (2013)", "oblivion_2013", "Extreme wide shot perched on glass edge of sky tower above cloud deck. Sitting in high-tech white scout suit with sniper rifle looking down at ruined Earth at pristine sunrise. Crystalline typography text \"OBLIVION\". 9:16 vertical poster."),
    ("Mad Max 2 (Gyro Captain) (1981)", "gyro_captain", "Medium shot beside skeletal autogyro flying contraption. Wearing sheepskin flight helmet and goggles, peering through binoculars over sandstone cliff into desert sandstorm. Rusted yellow typography text \"THE ROAD WARRIOR\". 9:16 vertical poster."),
    ("Waterworld (1995)", "waterworld_1995", "Low angle from bow of trimaran sailboat. Gripping steering ropes as vessel slices through endless deep blue post-apocalyptic sea in spray of white foam. Distressed metallic typography text \"WATERWORLD\". 9:16 vertical poster."),
    ("Equilibrium (2002)", "equilibrium_2002", "Symmetrical medium shot in white marble hall. In high-collared black cleric coat performing Gun Kata stance with muzzle flashes bursting from crossed handguns. Stylized cross typography text \"EQUILIBRIUM\". 9:16 vertical poster."),
    ("The Book of Eli (2010)", "book_of_eli", "Tracking shot walking desolate highway. In tattered hooded cowl, dark sunglasses, carrying machete and leather-bound braille Bible through radioactive wasteland. Weathered typography text \"THE BOOK OF ELI\". 9:16 vertical poster."),
    ("I, Robot (2004)", "i_robot_2004", "Circular low angle surrounded by hundreds of identical white NS-5 androids with glowing red chests staring in unison. Wearing leather jacket and black Converse holding futuristic sidearm. Sleek chrome typography text \"I, ROBOT\". 9:16 vertical poster."),
    ("Chappie (2015)", "chappie_2015", "Medium shot crouching beside graffiti-decorated police droid. Holding orange spray paint can in street apparel before colorful abandoned factory brick wall. Bold stencil typography text \"CHAPPIE\". 9:16 vertical poster."),
    ("District 9 (Mech Battle) (2009)", "district_9_mech", "Wide action shot in scrapyard. Piloting alien bipedal battle mech with half-alien transformed face, firing white gravity vortex blast scattering metal debris. Warning sign typography text \"DISTRICT 9\". 9:16 vertical poster."),
    ("Ready Player One (2018)", "ready_player_one", "Profile on rooftop of stacked shipping container towers. Wearing haptic VR visor, reaching hand out into glowing neon cyber gateway of the OASIS. 80s arcade maze typography text \"READY PLAYER ONE\". 9:16 vertical poster."),
    ("Alita: Battle Angel (2019)", "alita_battle_angel", "Dynamic low angle on Motorball circuit track. Armored in glossy carbon-fiber cyborg suit, Damascus steel blade glowing blue ready to slice mechanical opponent in stadium lights. Polished chrome typography text \"ALITA: BATTLE ANGEL\". 9:16 vertical poster."),
    ("Ghost in the Shell (1995)", "ghost_in_the_shell", "Worm's-eye view looking up at high skyscraper ledge. Thermoptic camouflage suit dissolving in torrential midnight rain reflecting millions of glowing Hong Kong neon signs. Digital green typography text \"GHOST IN THE SHELL\". 9:16 vertical poster."),
    ("Akira (1988)", "akira_1988", "Iconic rear shot walking. Wearing red leather motorcycle jacket with pill capsule patch on back, walking toward smoking red high-tech power-slide motorcycle in ruined Neo-Tokyo night. Blazing red typography text \"AKIRA\". 9:16 vertical poster."),
    ("Princess Mononoke (1997)", "princess_mononoke", "Eye-level in ancient mossy primeval forest. Red war paint stripes on face, bone dagger in hand, standing back-to-back with giant white wolf god as glowing forest spirits float in mist. Epic crimson typography text \"PRINCESS MONONOKE\". 9:16 vertical poster."),
    ("Spirited Away (2001)", "spirited_away", "Low angle from water surface. Standing along flooded railroad tracks submerged in tranquil turquoise ocean water, watching vintage red spirit train roll past at violet sunset. Whimsical soft typography text \"SPIRITED AWAY\". 9:16 vertical poster."),
    ("Howl's Moving Castle (2004)", "howls_moving_castle", "Extreme wide shot walking on air. Feathered sorcerer cloak billowing like giant black wings, strolling across sky above European timber-framed alpine village in golden afternoon light. Fairy-tale gold typography text \"HOWL'S MOVING CASTLE\". 9:16 vertical poster."),
    ("Castle in the Sky (1986)", "castle_in_the_sky", "Medium shot looking up into tempest. Blue levitation crystal pendant glowing on chest, casting vertical blue beam of light guiding path toward giant thundercloud concealing floating island Laputa. Azure typography text \"CASTLE IN THE SKY\". 9:16 vertical poster."),
    ("Nausicaä of the Valley of the Wind (1984)", "nausicaa_valley", "Action shot banking sharply on white jet-glider wings. Gliding inches above giant bioluminescent fungal trees releasing glowing golden spore clouds. Classic vintage typography text \"NAUSICAÄ\". 9:16 vertical poster."),
    ("Neon Genesis Evangelion (1995)", "neon_genesis_evangelion", "Tight close-up profile in cockpit flooded with orange LCL fluid. Colossal glowing purple and neon-green Eva-01 robotic eye opening menacingly behind cockpit glass. Century Gothic typography text \"NEON GENESIS EVANGELION\". 9:16 vertical poster.")
]

tasks = []
for i in range(50):
    movie_title, img_slug, prompt_desc = ideas[i]
    target_html = targets[i]
    tasks.append({
        'index': i + 206,
        'movie': movie_title,
        'slug': img_slug,
        'target_html': target_html,
        'prompt': f'Khóa dáng mặt Oval, gò má cao, đuôi mắt mí lót Á Đông có hồn, kiểu tóc spiky brush-up đặc trưng. {prompt_desc}'
    })

with open('movie_posters_tasks_batch_4.json', 'w', encoding='utf-8') as f:
    json.dump(tasks, f, ensure_ascii=False, indent=2)

print(f"Generated {len(tasks)} tasks for Batch 4 successfully.")
